.github/workflows/coverage.yaml

[CI] Add code coverage

---

README.md

* Add badges (not working until it is released actually)
* Add related repos
* Add more..

[README.md] Add badge and so on

---

.github/workflows/main.yml
arci-ros/src/ros_nav_client.rs

Building RosNavClient will be complexed.
This builder enable to keep it simple and
flexible in Rusty manner.

[arci-ros] Add RosNavClientBuilder

---

openrr-client/Cargo.toml
openrr-client/src/clients/ik_client.rs

[openrr-client] Add configs to create IkClient

---

openrr-client/Cargo.toml
openrr-client/src/clients/ik_client.rs

[openrr-client] Add constraints in IkClientConfig

---

Cargo.toml
openrr-apps/Cargo.toml
openrr-apps/src/bin/robot_command.rs
openrr-apps/src/error.rs
openrr-apps/src/lib.rs
openrr-apps/src/robot_client.rs
openrr-apps/src/robot_command.rs
openrr-apps/src/robot_config.rs

[openrr-apps] Add openrr_apps_robot_command

---

openrr-apps/src/robot_client.rs
openrr-apps/src/robot_command.rs

- support ik_clinet in current_joint_positions / send_joint_positions
- add transform

[openrr-apps] Refactor RobotClient

---

openrr-apps/config/ur10_cmd.txt
openrr-apps/config/ur10_cmd_collision.txt
openrr-apps/config/ur10_cmd_ik.txt
openrr-apps/config/ur10_cmd_joints.txt
openrr-apps/config/ur10_ros.toml
openrr-apps/config/ur10_urdf_viz.toml

[openrr-apps] Add ur10 sample for openrr_apps_robot_command

---

arci/src/traits/joint_trajectory_client.rs
arci/tests/test_waits.rs

ひとまずprを作ってみてcodecov.ioで見れるかテスト

[arci] Add tests for EachJointDiffCondition

---

.github/workflows/main.yml
Cargo.toml
arci-gamepad-gilrs/Cargo.toml
arci-ros/Cargo.toml
arci-urdf-viz/Cargo.toml
arci-urdf-viz/src/client.rs
arci-urdf-viz/src/utils.rs
arci-urdf-viz/tests/test_web.rs
arci/Cargo.toml
openrr-apps/Cargo.toml
openrr-client/Cargo.toml
openrr-teleop/Cargo.toml

Update tokio to 1.0

---

arci/src/clients/joint_velocity_limiter.rs

[arci] Fix cargo doc warning

---

arci-urdf-viz/tests/test_client.rs

Testing arci urdf viz

---

openrr-apps/README.md

* Fix typo
* Add install of urdf-viz
* Add how to build

[openrr-apps] Update README

---

arci-ros/Cargo.toml
arci-urdf-viz/Cargo.toml
arci/Cargo.toml
openrr-client/Cargo.toml

Context: https://github.com/openrr/openrr/pull/98#discussion_r564309577

Sort dependencies

---

arci-gamepad-gilrs/src/lib.rs

Refs #120
I tries to fix this, but I couldn't.
So I decided to just disable it on MacOS.

[arci-gamepad-gilrs] Disable connection check for macos

---

openrr-client/src/clients/ik_client.rs
openrr-client/src/robot_client.rs

- use IkSolverWithChain's chain

[openrr-client] Remove IkClient chain

---

openrr-gui/src/joint_position_sender.rs

[openrr-gui] Change Center to Zero

---

openrr-gui/src/joint_position_sender.rs

[openrr-gui] Change duration of send_joint_positions to 100 milliseconds

---

README.md

before: https://github.com/openrr/openrr#joint_trajectory_sender
after: https://github.com/openrr/openrr/tree/taiki-e/img-size#joint_trajectory_sender

Adjust joint_sender image size

---

arci-gamepad-gilrs/Cargo.toml
arci-ros/Cargo.toml
arci-speak-cmd/Cargo.toml
arci-urdf-viz/Cargo.toml
arci/Cargo.toml
openrr-apps/Cargo.toml
openrr-client/Cargo.toml
openrr-command/Cargo.toml
openrr-gui/Cargo.toml
openrr-planner/Cargo.toml
openrr-sleep/Cargo.toml
openrr-teleop/Cargo.toml
openrr/Cargo.toml

Add more cargo information to release v0.0.1

---

openrr-apps/README.md
openrr-apps/src/bin/joint_position_sender.rs

* add arci_ros::init() to initialize ROS
* use the path of config instead of arguments
closes #162

Update joint positions sender

---

openrr-client/tests/test_ik_client.rs
openrr-planner/sample.urdf
openrr-planner/src/ik.rs
openrr-planner/src/planner/joint_path_planner.rs

This is to make it easy to how collision checking.
* large root body to make it easy to collide with arm
* large joint range for the same reason
* fix test for that change

[openrr-planner] Update sample model

---

arci-ros/src/ros_nav_client.rs
openrr-apps/src/bin/robot_teleop.rs
openrr-apps/src/robot_config.rs
openrr-planner/src/planner/joint_path_planner.rs

Solve clippy warnings

---

.github/workflows/main.yml
Cargo.toml
README.md
arci-speak-audio/Cargo.toml
arci-speak-audio/README.md
arci-speak-audio/examples/audio_speak.rs
arci-speak-audio/src/lib.rs

- add arci-speak-audio for playing audio files

[arci-speak-audio] add "arci-speak-audio" crate

---

arci-speak-audio/Cargo.toml
arci-speak-cmd/Cargo.toml

- Fixed versions of arci-speak-cmd and arci-speak-audio to 0.0.1

[arci-speak-cmd][arci-speak-audio] fix versions in Cargo.toml to 0.0.1

---

openrr-apps/src/error.rs
openrr-apps/src/robot_config.rs
openrr-client/src/robot_client.rs

- to use robot client / config only with navigation

[openrr-client, openrr-apps] Make urdf path and clients configs optional

---

.github/workflows/coverage.yaml
.github/workflows/ros1.yaml

[.github] Fix CI

---

arci-gamepad-gilrs/Cargo.toml
arci-ros/Cargo.toml
arci-speak-audio/Cargo.toml
arci-speak-cmd/Cargo.toml
arci-urdf-viz/Cargo.toml
arci/Cargo.toml
openrr-apps/Cargo.toml
openrr-client/Cargo.toml
openrr-command/Cargo.toml
openrr-gui/Cargo.toml
openrr-planner/Cargo.toml
openrr-sleep/Cargo.toml
openrr-teleop/Cargo.toml
openrr/Cargo.toml

arci-ros v0.0.1 does not work on MacOS.
This release will make it possible.

Release v0.0.3

---

openrr-apps/Cargo.toml
openrr-apps/README.md
openrr-apps/src/bin/joint_position_sender.rs
openrr-apps/src/bin/robot_command.rs
openrr-apps/src/bin/robot_teleop.rs
openrr-apps/src/lib.rs
openrr-apps/src/utils.rs

[openrr-apps] Introduce utils and env var

---

.github/workflows/main.yml
openrr-apps/Cargo.toml
openrr-apps/README.md
openrr/Cargo.toml

* closes #158 
* Update README.md for openrr-apps

[openrr-apps] Enalbe ros feature as default

---

.github/workflows/main.yml
openrr-apps/src/error.rs
openrr-apps/src/robot_config.rs
openrr-apps/tests/test_robot_config.rs

[openrr-apps] Return error if config requires ros feature but ros feature is disabled

---

.github/workflows/coverage.yaml

https://github.com/openrr/openrr/runs/2037069992?check_suite_focus=true

[workflows] Pin nightly toolchain to nightly-2021-03-04

---

arci-speak-audio/Cargo.toml

Fix author's name and mail address of `arci-speak-audio`

[arci-speak-audio] fix author of arci-speak-audio

---

arci-gamepad-gilrs/Cargo.toml
arci-ros/Cargo.toml
arci-speak-audio/Cargo.toml
arci-speak-cmd/Cargo.toml
arci-urdf-viz/Cargo.toml
arci/Cargo.toml
openrr-apps/Cargo.toml
openrr-client/Cargo.toml
openrr-command/Cargo.toml
openrr-gui/Cargo.toml
openrr-planner/Cargo.toml
openrr-sleep/Cargo.toml
openrr-teleop/Cargo.toml
openrr/Cargo.toml

Release v0.0.4

---

arci-gamepad-gilrs/Cargo.toml
arci-ros/Cargo.toml
arci-speak-audio/Cargo.toml
arci-speak-cmd/Cargo.toml
arci-urdf-viz/Cargo.toml
arci/Cargo.toml
ci/publish.sh
openrr-apps/Cargo.toml
openrr-client/Cargo.toml
openrr-command/Cargo.toml
openrr-gui/Cargo.toml
openrr-planner/Cargo.toml
openrr-sleep/Cargo.toml
openrr-teleop/Cargo.toml
openrr/Cargo.toml
tools/update-version.sh

The first commit adds a useful script to update version in Cargo.toml.
The second commit updates versions in Cargo.toml by using that script.

Release v0.0.5

---

.github/workflows/coverage.yaml

Update actions/checkout to v2

---

arci-urdf-viz/Cargo.toml
arci-urdf-viz/tests/web_server.rs

The same as https://github.com/openrr/urdf-viz/pull/50

[arci-urdf-viz] Migrate to actix-web from rouille

---

.github/workflows/main.yml
arci-urdf-viz/tests/test_client.rs
arci-urdf-viz/tests/web_server.rs
openrr-client/tests/test_ik_client.rs
openrr-planner/examples/reach.rs

Addresses https://github.com/openrr/openrr/pull/244#pullrequestreview-626733552

[workflows] Apply clippy for tests and examples

---

.github/workflows/coverage.yaml

grcov is not improved.
I gave up waiting it improved.

[CI] Go back to tarpaulin for coverage

---

openrr-gui/src/joint_position_sender.rs

After #248, there is no reason to do this in an async block.

[openrr-gui] Send positions within the update method

---

arci/src/traits/joint_trajectory_client.rs
arci/src/traits/speaker.rs

[arci] Add implementation note to some trait methods

---

arci-ros/src/error.rs
arci-ros/src/ros_nav_client.rs
arci/src/error.rs

[arci-ros] Handle wait-related error in RosNavClient::send_goal_pose

---

arci-gamepad-gilrs/src/lib.rs

The thread does not terminate when the `JoinHandle` is dropped and continues to run until the end of the given closure or the program.
So, the background thread will continue to watch the event after the `GilGamepad` is dropped and will try to send the event through the channel. However, since the receiver has already been dropped as a part of `GilGamepad`, sending to the channel will fail and the background thread will panic.

[arci-gamepad-gilrs] Stop background thread when dropping

---

arci/src/clients/joint_trajectory_clients_container.rs

- ``fn current position``
- ok pattern
- err pattern
- ``fn send position``
- ok pattern
- err pattern
Remaking pull request.

add test for JointTrajectoryClientsContainer

---

.github/workflows/main.yml

https://github.com/openrr/openrr/runs/2434145731?check_suite_focus=true

[workflows] Fix installation of rustfmt

---

arci-ros/src/lib.rs
arci-urdf-viz/src/lib.rs
arci/src/lib.rs
openrr-apps/src/lib.rs
openrr-client/src/lib.rs
openrr-command/src/lib.rs
openrr-gui/src/lib.rs
openrr-planner/src/lib.rs
openrr-sleep/src/lib.rs
openrr-teleop/src/lib.rs

https://github.com/openrr/openrr/blob/1dc6dfe09c82e91b21a9c3ce1e6aae887276e924/arci/src/lib.rs#L9-L16

Group exports from modules

---

arci/src/clients.rs
arci/src/clients/dummy_localization.rs
arci/src/clients/dummy_move_base.rs
arci/src/clients/dummy_navigation.rs
arci/src/clients/dummy_speaker.rs
arci/src/clients/dummy_trajectory_client.rs

[arci] Add DummySpeaker

---

arci-urdf-viz/tests/test_client.rs
arci-urdf-viz/tests/web_server.rs

ports https://github.com/openrr/urdf-viz/pull/67

[arci-urdf-viz] Reduce uses of Arc in WebServer

---

openrr-plugin/src/lib.rs
openrr-plugin/src/proxy.rs

[openrr-plugin] impl Debug for all public types

---

openrr-plugin/benches/proxy.rs
openrr-plugin/src/lib.rs

[openrr-plugin] Add PluginProxy::from_path

---

arci-urdf-viz/src/client.rs
openrr-apps/src/robot_config.rs
openrr-client/src/robot_client.rs

[arci-urdf-viz] Add create_joint_trajectory_clients_lazy

---

arci-ros/README.md

addresses https://github.com/openrr/openrr/pull/111#discussion_r565163844

[arci-ros] Add license section to readme

---

arci/src/clients/partial_joint_trajectory_client.rs

creating test function for partial joint trajectory client

Add test for partial joint trajectory client

---

openrr-plugin/benches/proxy.rs
openrr-plugin/examples/load_plugin.rs
openrr-plugin/examples/plugin/Cargo.toml
openrr-plugin/examples/plugin/src/lib.rs
openrr-plugin/src/lib.rs
openrr-plugin/src/proxy.rs

- Return Result
- Require Send + Sync
split from #319

[openrr-plugin] Change Plugin trait interface

---

openrr-apps/Cargo.toml
openrr-apps/config/pr2_robot_client_config_for_ros.toml
openrr-apps/config/sample_robot_client_config_for_plugin.toml
openrr-apps/config/sample_teleop_config_plugin.toml
openrr-apps/config/ur10_robot_client_config_for_ros.toml
openrr-apps/schema/robot_config.json
openrr-apps/schema/robot_teleop_config.json
openrr-apps/src/bin/robot_teleop.rs
openrr-apps/src/error.rs
openrr-apps/src/robot_config.rs
openrr-apps/src/robot_teleop_config.rs
openrr-config/src/lib.rs
openrr-plugin/examples/load_plugin.rs
openrr-plugin/src/lib.rs

Closes #312
```sh
cargo build -p openrr-plugin-example
cargo run -p openrr-apps --bin openrr_apps_joint_position_sender -- \
--config-path ./openrr-apps/config/sample_robot_client_config_for_plugin.toml
```

[openrr-apps] Support plugin

---

.github/workflows/main.yml

Fix a typo

---

.github/workflows/coverage.yaml
arci-urdf-viz/tests/test_client.rs

Switch to [cargo-llvm-cov](https://github.com/taiki-e/cargo-llvm-cov).
~~Depend on #344~~

Switch to cargo-llvm-cov

---

arci-ros/src/ros_control_client.rs
arci-urdf-viz/tests/test_client.rs
openrr-client/src/clients/local_move.rs
openrr-client/tests/test_ik_client.rs

https://rust-lang.github.io/rust-clippy/master/index.html#search_is_some
https://rust-lang.github.io/rust-clippy/master/index.html#bool_assert_comparison

Fix to pass clippy

---

arci-urdf-viz/src/client.rs
arci-urdf-viz/tests/test_client.rs
arci/src/clients/partial_joint_trajectory_client.rs
arci/src/error.rs

change return ``Result``
test setting

Improve `fn new`

---

.github/workflows/main.yml
.github/workflows/release.yml
openrr-planner/Cargo.toml
openrr-planner/src/collision/mesh.rs

refs: https://github.com/openrr/urdf-viz/pull/82

[openrr-planner] Support stl without assimp

---

.github/workflows/coverage.yaml
.github/workflows/ros2.yaml
arci-ros2/Cargo.toml
arci-ros2/README.md
arci-ros2/examples/cmd_vel.rs
arci-ros2/examples/navigation.rs
arci-ros2/src/cmd_vel_move_base.rs
arci-ros2/src/lib.rs
arci-ros2/src/navigation.rs
arci-ros2/src/plugin.rs
arci-ros2/tests/test_cmd_vel.rs
arci/src/lib.rs
openrr-apps/config/turtlebot3_robot_client_config_ros2.toml

[arci-ros2] Implement ROS2 navigation2 send_goal_pose

---

openrr-planner/Cargo.toml
openrr-planner/src/collision/mesh.rs

See https://github.com/openrr/urdf-viz/pull/88 for details.

[openrr-planner] Use nom_stl instead of stl_io

---

arci-ros/src/ros_control_action_client.rs
arci-ros/src/ros_control_client.rs
arci/src/clients/joint_position_limiter.rs
arci/src/clients/partial_joint_trajectory_client.rs
arci/src/error.rs

Please, check the specification of function

Improvement partial clients

---

.github/workflows/coverage.yaml
.github/workflows/main.yml

It fails to download on nightly tool chains.
I don't know this really solve the problem.

[CI] Fix rustfmt and coverage

---

arci-ros/Cargo.toml
arci-ros/examples/cmd_vel.rs
arci-ros/tests/test_cmdvel_base.rs

Add test for arci-ros MoveBase

---

arci/src/traits/move_base.rs
openrr-teleop/Cargo.toml
openrr-teleop/src/move_base.rs
openrr-teleop/src/robot_command_executor.rs

Add test function
- `fn get`(function name is not same. )
- `fn proc`
four type variation test

[openrr-teleop] Add test for `move_base`

---

arci-urdf-viz/Cargo.toml
arci-urdf-viz/src/client.rs
arci-urdf-viz/src/utils.rs
arci-urdf-viz/tests/test_web.rs
arci/src/lib.rs
openrr-plugin/Cargo.toml
openrr-plugin/src/proxy.rs
openrr-plugin/tests/proxy.rs

[arci] Re-export nalgebra

---

openrr-client/src/clients/collision_avoidance_client.rs

Ref: https://github.com/openrr/openrr/blob/4d6b2f3a29d8d7a29d3ded04bddb3ccbe8edb6d3/openrr-client/src/clients/collision_check_client.rs#L65

[openrr-client] Add a function creating CollisionAvoidanceClient

---

openrr-apps/src/bin/joint_position_sender.rs
openrr-apps/src/bin/robot_command.rs
openrr-apps/src/bin/robot_teleop.rs
openrr-apps/src/bin/velocity_sender.rs
openrr-apps/src/utils.rs

Addresses https://github.com/openrr/openrr/pull/408#pullrequestreview-719886603

[openrr-apps] Clean up config-related code

---

arci-ros/src/ros_control_client.rs
arci/src/clients/joint_position_limiter.rs

-  for `fn new_joint_position_limiter`

[arci-ros] Create test for new_joint_position_limiter

---

arci-gamepad-gilrs/Cargo.toml
arci-gamepad-gilrs/examples/gilrs_check_keymap.rs
arci-gamepad-gilrs/src/lib.rs
arci/src/traits/gamepad.rs
openrr-plugin/src/proxy.rs
openrr-teleop/src/ik.rs
openrr-teleop/src/joints.rs
openrr-teleop/src/joints_pose_sender.rs
openrr-teleop/src/move_base.rs
openrr-teleop/src/robot_command_executor.rs

- check gamepad connection
- send events when connected or disconnected
- handle disconnected events at teleop control nodes

Check gamepad connection

---

openrr-teleop/src/ik.rs
openrr-teleop/src/joints.rs

[openrr-teleop] Add test for `default function`

---

README.md
arci-gamepad-gilrs/src/lib.rs
arci-gamepad-keyboard/src/lib.rs
arci-ros/src/lib.rs
arci-ros2/src/lib.rs
arci-speak-audio/src/lib.rs
arci-speak-cmd/src/lib.rs
arci-urdf-viz/src/lib.rs
arci/src/lib.rs
openrr-apps/src/lib.rs
openrr-client/src/lib.rs
openrr-command/src/lib.rs
openrr-config/src/lib.rs
openrr-gui/src/lib.rs
openrr-planner/Cargo.toml
openrr-planner/README.md
openrr-planner/src/lib.rs
openrr-plugin/src/lib.rs
openrr-remote/src/lib.rs
openrr-sleep/src/lib.rs
openrr-teleop/src/lib.rs
openrr/src/lib.rs

https://blog.rust-lang.org/2021/07/29/Rust-1.54.0.html#attributes-can-invoke-function-like-macros

Use readme as crate-level docs

---

arci-ros2/Cargo.toml
openrr-plugin/Cargo.toml
openrr-plugin/examples/plugin/Cargo.toml
openrr-plugin/src/gen/api.rs
openrr-plugin/src/lib.rs
openrr-plugin/src/proxy.rs
tools/codegen/src/plugin.rs

Update abi_stable to 0.10

---

arci-gamepad-keyboard/examples/keyboard_check_keymap.rs
openrr-apps/src/bin/robot_teleop.rs
openrr-client/src/error.rs
openrr-teleop/src/control_nodes_config.rs
openrr-teleop/src/ik.rs

[openrr-teleop] Add test for `control node`

---

openrr-plugin/Cargo.toml
openrr-plugin/src/proxy.rs

abi_stable 0.10.3 added support for floats.

[openrr-plugin] Update abi_stable to 0.10.3

---

arci/src/clients/joint_trajectory_clients_container.rs
arci/src/waits.rs

https://github.com/openrr/openrr/runs/4100330479?check_suite_focus=true#step:7:558

Fix newly added warnings in nightly

---

openrr-apps/command/pr2_cmd_ros.txt
openrr-apps/command/pr2_cmd_urdf_viz.txt
openrr-apps/command/sample_cmd_urdf_viz.txt
openrr-apps/command/ur10_cmd_ros.txt
openrr-apps/command/ur10_cmd_urdf_viz.txt

Fix sample commands

---

.github/actions/spelling/expect.txt
arci-ros/tests/test_control_client.rs

[arci-ros]Add test for `RosControlClient`

---

.github/actions/spelling/expect.txt
arci-gamepad-keyboard/examples/keyboard_check_keymap.rs
arci-ros2/Cargo.toml
arci-ros2/examples/navigation.rs
arci-ros2/examples/ros2_cmd_vel.rs
arci-ros2/src/lib.rs
arci-ros2/src/navigation.rs
arci-ros2/tests/test_cmd_vel.rs
arci-ros2/tests/test_navigation.rs
ci/publish.sh

[arci-ros2] Update r2r

---

arci-ros2/tests/test_navigation.rs

https://github.com/openrr/openrr/runs/4204162901?check_suite_focus=true

[arci-ros2] Fix flaky navigation test

---

arci-ros2/Cargo.toml
arci-ros2/tests/test_navigation.rs
arci-urdf-viz/Cargo.toml
arci-urdf-viz/tests/test_client.rs
arci-urdf-viz/tests/test_web.rs

https://github.com/denoland/flaky_test

Use flaky_test crate

---

arci-ros/Cargo.toml
arci-ros/tests/test_rosrust_utils.rs
arci-urdf-viz/tests/test_web.rs

https://github.com/openrr/openrr/runs/4281499279?check_suite_focus=true

[arci-ros] Mark test_subscribe_with_channel test as flaky

---

.github/workflows/ci.yml
.github/workflows/coverage.yml

https://github.com/Swatinem/rust-cache

[workflows] Use Swatinem/rust-cache action

---

arci-ros2/tests/test_navigation.rs
arci-urdf-viz/tests/test_client.rs
arci-urdf-viz/tests/test_web.rs

https://github.com/openrr/openrr/runs/4501291981?check_suite_focus=true

Fix "Address already in use" error in tests

---

openrr-client/src/clients/collision_avoidance_client.rs
openrr-planner/src/planner/joint_path_planner.rs

This PR adds JointPathPlannerConfig, in order to implement config-based creation of JointPathPlanner whose parameters can be set from TOML files easily via serde.

Add JointPathPlannerConfig and use it for client creation

---

openrr-client/src/clients/collision_check_client.rs
openrr-client/src/robot_client.rs
openrr-planner/src/collision/self_collision_checker.rs

Use RobotCollisionDetector in SelfCollisionChecker

---

openrr-client/src/clients/collision_check_client.rs
openrr-client/src/robot_client.rs
openrr-planner/src/collision/self_collision_checker.rs

This reverts commit 145d3c9263939415cc0beba8c57c7582b98cc1a2.

Revert "Use RobotCollisionDetector in SelfCollisionChecker"

---

arci-ros2/src/cmd_vel_move_base.rs
arci-ros2/src/navigation.rs

Addresses https://github.com/openrr/openrr/pull/551#discussion_r774226649

[arci-ros2] Add from_node constructor to clients

---

openrr-apps/src/utils.rs

output example:
```
2022-01-20T04:15:25.912376Z  WARN openrr_apps::utils: config ./openrr-apps/config/sample_robot_client_config_for_urdf_viz.toml is not valid TOML: unexpected character found: `$` at line 44 column 1
```

[openrr-apps] Warn TOML config that is not valid as TOML

---

openrr-planner/Cargo.toml
openrr-planner/src/collision/mesh.rs

https://github.com/openrr/mesh-loader
https://github.com/openrr/urdf-viz/pull/123

Switch to mesh-loader

---

openrr-gui/Cargo.toml
openrr-gui/src/joint_position_sender.rs
openrr-gui/src/style.rs
openrr-gui/src/velocity_sender.rs

Update iced to 0.4

---

openrr-planner/src/collision/collision_detector.rs

This PR adds a test of `detect_self` function in CollisionDetector.

[openrr-planner] Add a test for self collision detection

---

openrr-apps/command/sample_cmd_urdf_viz.txt

Change sample command for clap

---

arci-urdf-viz/Cargo.toml
arci-urdf-viz/tests/test_client.rs
arci-urdf-viz/tests/test_web.rs
arci-urdf-viz/tests/util/mod.rs
openrr-planner/Cargo.toml

depend on https://github.com/openrr/urdf-viz/pull/146.

Update urdf-viz to 0.37

---

openrr-planner/sample.urdf
openrr-planner/src/collision/collision_detector.rs
openrr-planner/src/collision/robot_collision_detector.rs
openrr-planner/src/collision/self_collision_checker.rs
openrr-planner/src/ik.rs

This PR is an alternate of #608 .
The second arm is added to the sample robot.

Openrr planner/change sample model2

---

openrr-apps/src/bin/robot_command.rs

Add test for sample command parsed by robot_command in openrr-apps.

Add test for sample command

---

.github/actions/spelling/expect.txt
.github/workflows/ci.yml
openrr-plugin/src/gen/api.rs
openrr-plugin/src/gen/proxy.rs
openrr-plugin/src/lib.rs
openrr-plugin/src/proxy.rs
openrr-remote/src/gen/impls.rs
openrr-remote/src/lib.rs
tools/codegen/Cargo.toml
tools/codegen/src/main.rs
tools/codegen/src/plugin.rs
tools/codegen/src/rpc.rs

Remove dependency on rustfmt & nightly toolchain.
refs: https://github.com/dtolnay/prettyplease

[tools/codegen] Use prettyplease instead of calling rustfmt

---

openrr-apps/command/pr2_cmd_collision.txt
openrr-apps/command/pr2_cmd_ik.txt
openrr-apps/command/pr2_cmd_joints.txt
openrr-apps/command/pr2_cmd_ros.txt
openrr-apps/command/pr2_cmd_urdf_viz.txt
openrr-apps/command/ur10_cmd_collision.txt
openrr-apps/command/ur10_cmd_ik.txt
openrr-apps/command/ur10_cmd_joints.txt
openrr-apps/command/ur10_cmd_ros.txt
openrr-apps/command/ur10_cmd_urdf_viz.txt
openrr-apps/src/bin/robot_command.rs

I implemented test for sample command which is read by openrr_apps_robot_command and update some sample commands.

Update test for openrr_apps_robot_command

---

openrr-client/src/clients/collision_check_client.rs
openrr-planner/src/collision/self_collision_checker.rs

This PR is a modified version of #544 , which was reverted in #550 .
The purpose of this PR is introducing a robot model only used for collision checking. The current design shares only one robot model, and the model is used for various applications, e.g. collision checking, planning, solving FK and IK. This is too complicated, and we need to pay attention to what the robot states corresponds to (current pose? target pose?). Introducing a task-focused model can be a solution of this complexity.
Note: I checked that all tests of our private development passed with this change.

[openrr-planner] Use RobotCollisionDetector in SelfCollisionChecker

---

openrr-planner/src/collision/collision_detector.rs

This PR implements an AABB (Axis Aligned Bounding Box)-based sweep and prune algorithm for environmental collision checking, as same as #630 .
We can evaluate the improvement in computational time with the following command:
```bash
cargo bench bench_check_environmental_collisions
```
The comparison result in my environment is:
```
[Before]
bench_check_environmental_collisions                        
time:   [362.01 us 362.96 us 363.89 us]
[After (this PR is applied)]
bench_check_environmental_collisions                        
time:   [12.597 us 12.633 us 12.670 us]
change: [-96.604% -96.553% -96.508%] (p = 0.00 < 0.05)
Performance has improved.
```

[openrr-planner] Use AABB-based pruning in environmental collision checking

---

openrr-planner/examples/reach.rs

This PR fixes undesirable behaviors observed on planning failures in the reaching example, by restoring the joint positions.
Furthermore, this PR unifies all procedures updating the robot: the update is executed only once at the beginning of the while-loop, referring to the trajectory point stack named `plans`.

[openrr-planner] Fix "reach" example

---

openrr-apps/README.md
openrr-teleop/README.md

I update `README` of openrr-teleop.

Add gamepad usage to openrr-teleop readme

---

.github/actions/spelling/expect.txt
openrr-apps/README.md
openrr-apps/config/irobot_create/irobot_create_dock_command.txt
openrr-apps/config/irobot_create/irobot_create_drive_distance.txt
openrr-apps/config/irobot_create/irobot_create_undock_command.txt
openrr-apps/config/irobot_create_robot_client_config_ros2.toml
openrr-apps/config/irobot_create_teleop_config_ros2.toml

I added sample configs for iRobot Create and update README file to describe usage of them.

Update openrr-apps for Create

---

openrr-command/src/robot_command.rs

The purpose of this PR is to fix https://github.com/openrr/openrr/issues/643
Edit RobotCommand to remove `\"` and recover `  ` (space) that are required for the argument in the string.
This PR is reopened PR #650

Add function to edit RobotCommand

---

.github/actions/spelling/expect.txt
.github/workflows/spelling.yml

```
Error: Failed to retrieve cspell:cpp/cpp.txt;cspell:filetypes/filetypes.txt -- https://raw.githubusercontent.com/check-spelling/cspell-dicts/v20220427/dictionaries/cpp/cpp.txt;cspell:filetypes/filetypes.txt
```

Fix check-spelling

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/release.yml
openrr-remote/Cargo.toml
openrr-remote/src/lib.rs

- prost-build 0.10 -> 0.11
- prost 0.10 -> 0.11
- tonic-build 0.7 -> 0.8
- tonic 0.7 -> 0.8

Update tonic and prost

---

openrr-client/src/clients/collision_check_client.rs
openrr-planner/src/collision/self_collision_checker.rs

In current implementation, we need to build a sub-chain of robot model held for collision checking,to specify joints. This PR changes the implementation and enables us to specify joints by name instead.
With this change, we can make all SelfCollisionChecker's fields private.

[openrr-planner] Change SelfCollisionChecker APIs

---

openrr-apps/schema/robot_config.json
openrr-apps/schema/robot_teleop_config.json
tools/update-schema.sh

The latest shema updated commit #662 was not sufficient. I fix command argument in `tools/update-schema` and execute it to update shema files.

[tools] Fix update-schema.sh

---

.github/workflows/ci.yml

refs: https://github.com/actions/runner-images/issues/6002

Remove uses of GitHub provided ubuntu-18.04 runner

---

openrr-apps/src/bin/joint_position_sender.rs
openrr-apps/src/bin/velocity_sender.rs

See https://github.com/openrr/openrr-tutorial/pull/1#discussion_r963220796 for the context.

[openrr-apps] Hide --theme option from help message

---

.github/workflows/ci.yml

This reverts commit 330acf8a7c2ac6c484e26140d1fb2ffa19098935.

Revert "Fix CI failure on melodic"

---

openrr-command/src/robot_command.rs

[openrr-command] Add attribute to allow only used in recursion

---

openrr-planner/src/planner/joint_path_planner.rs

The used APIS were added in #690.

[openrr-planner] Refactor JointPathPlanner with its new APIs

---

openrr-client/src/clients/collision_avoidance_client.rs

Because JointPathPlanner APIs are changed to use joint names instead of sub-chains in #671, using_joints field is no longer required.

[openrr-client] Remove using_joints from CollisionAvoidanceClient

---

openrr-planner/src/collision/self_collision_checker.rs
openrr-planner/src/planner/joint_path_planner.rs

resolves https://github.com/openrr/openrr/pull/704#discussion_r999169766

[openrr-planner] Change comments to doc comments

---

openrr-apps/src/bin/robot_teleop.rs

I test this and add arci_ros::init, then change some layout.

[openrr-apps] Fix JoyGamepad layout for openrr_apps_robot_teleop

---

.github/workflows/ci.yml

It seems that r2r is fixed for me.

Recover foxy support

---

.github/dependabot.yml
arci-speak-audio/Cargo.toml
arci-speak-cmd/Cargo.toml
openrr-apps/Cargo.toml
openrr-apps/src/bin/config.rs
openrr-apps/src/bin/joint_position_sender.rs
openrr-apps/src/bin/robot_command.rs
openrr-apps/src/bin/robot_teleop.rs
openrr-apps/src/bin/velocity_sender.rs
openrr-command/Cargo.toml
openrr-command/src/robot_command.rs
openrr-planner/Cargo.toml
openrr-planner/examples/reach.rs
openrr-teleop/Cargo.toml

Reverts https://github.com/openrr/openrr/pull/719

Revert "Revert "Update clap from 3.1 to 4.0""

---

arci-ros/examples/joy_gamepad_example.rs
arci-ros/src/joy_gamepad.rs
arci-ros/tests/test_joy.rs
openrr-apps/config/sample_teleop_config_urdf_viz_joy_gamepad.toml
openrr-apps/src/bin/robot_teleop.rs
openrr-apps/src/robot_teleop_config.rs

Addresses https://github.com/openrr/openrr-tutorial/pull/1#discussion_r963214012.
TODO:
- ~~needs test~~
- ~~decide the default setting: https://github.com/openrr/openrr/pull/707#discussion_r1000446877~~ #708 
- ~~support custom setting (probably: add JoyGamepadConfig to arci-ros and use it in teleop config)~~

[openrr-apps] Support JoyGamepad for robot_teleop

---

openrr-command/src/robot_command.rs

This PR just complements the PR #697 by updating RobotCommand implementation.

[openrr-command] Print collision avoidance clients with 'List' command

---

.github/workflows/ci.yml
.github/workflows/coverage.yml

follow-up https://github.com/openrr/openrr/pull/737
Example of the report:
```
error: duplicated words in .github/.cspell/dictionary.txt
=======================================
yaml
=======================================
```

Check duplications in dictionary

---

.github/workflows/ci.yml

This reverts commit de81e52f6a0e87abf82ee81970d617154889bee1.

Revert "Workaround GitHub Actions bug on Windows"

---

.github/workflows/ci.yml
arci-ros2/src/cmd_vel_move_base.rs
arci-ros2/src/navigation.rs
arci-ros2/src/ros2_control.rs

Limit test threads in ROS2 tests

---

.deny.toml
.github/.cspell/project-dictionary.txt
arci-speak-audio/Cargo.toml

Addresses an advisory from transitively dep of rodio.

[arci-speak-audio] Disable default-features of rodio

---

.github/workflows/coverage.yml
Cargo.toml
arci-gamepad-gilrs/Cargo.toml
arci-gamepad-keyboard/Cargo.toml
arci-ros/Cargo.toml
arci-ros/tests/hygiene/Cargo.toml
arci-ros2/Cargo.toml
arci-speak-audio/Cargo.toml
arci-speak-cmd/Cargo.toml
arci-urdf-viz/Cargo.toml
arci/Cargo.toml
openrr-apps/Cargo.toml
openrr-client/Cargo.toml
openrr-command/Cargo.toml
openrr-config/Cargo.toml
openrr-gui/Cargo.toml
openrr-planner/Cargo.toml
openrr-plugin/Cargo.toml
openrr-plugin/examples/plugin/Cargo.toml
openrr-remote/Cargo.toml
openrr-teleop/Cargo.toml
openrr/Cargo.toml
tools/codegen/Cargo.toml

Refs:
- https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table
- https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace

Use workspace inheritance for dependencies

---

arci-ros/tests/test_localization_client.rs
arci-ros/tests/test_robot_client.rs
arci-ros/tests/test_speak_client.rs

[arci-ros] Fix attribute of some tests for arci-ros

---

README.md

Like below. Add batch to link of `OpenRR Turorial`.

Add batch to README

---

ci/publish.sh
openrr-remote/build.rs
openrr-remote/src/lib.rs
tools/gen-code.sh

[openrr-remote] Fix cargo publish error

---

.github/workflows/ci.yml

This reverts commit bb54b17bb31956e9863c29465e370da539bf0983.

Revert "Workaround GitHub Actions bug on macOS"

---

.github/dependabot.yml
Cargo.toml
openrr-gui/src/joint_position_sender.rs
openrr-planner/src/collision/urdf.rs

~~Depend on ~~https://github.com/openrr/k/pull/116 and https://github.com/openrr/urdf-viz/pull/207~~ https://github.com/openrr/urdf-viz/pull/208.~~

Update urdf-rs, k, and urdf-viz

---

arci-ros/src/cmd_vel_move_base.rs

Updated due to inability to handle errors.

[arci-ros] Update Movebase error

---

Cargo.toml

This reverts commit 06ee5a4871506abbef7d0e54c159e4e8dfc508d4.

Revert "Pin r2r to 0.7.0"

---

openrr-gui/src/velocity_sender.rs

[openrr-gui] Fix theta for velocity_sender

---

openrr-apps/config/pr2_robot_client_config_for_ros.toml
openrr-apps/config/pr2_robot_client_config_for_urdf_viz.toml
openrr-apps/config/sample_robot_client_config_for_plugin.toml
openrr-apps/config/ur10_robot_client_config_for_ros.toml
openrr-apps/config/ur10_robot_client_config_for_urdf_viz.toml

Improve configs for collision checking

---

arci-ros2/src/lib.rs
arci-ros2/src/plugin.rs
arci-ros2/src/ros2_laser_scan.rs
arci-ros2/tests/test_ros2_laser_scan.rs

Add `Ros2LaserScan2D`

---

.github/workflows/ci.yml
arci-ros2/README.md
arci-ros2/src/navigation.rs
arci-ros2/src/ros2_control.rs
arci-ros2/src/ros2_laser_scan.rs
arci-ros2/src/utils.rs
arci-ros2/tests/test_navigation.rs
openrr-tracing/src/de.rs

- Update docs to refer to humble instead of foxy that was EoL on 2023-06-20.
- Add a helper to simplify the code.

[arci-ros2] Update

---

arci-speak-audio/LICENSE
openrr-base/LICENSE

Add license files to arci-speak-audio and openrr-base

---

arci-ros2/src/lib.rs
arci-ros2/src/plugin.rs
arci-ros2/src/ros2_localization_client.rs
arci-ros2/tests/test_ros2_localization_client.rs

Add `Ros2LocalizationClient`

---

.github/.cspell/rust-dependencies.txt
.github/workflows/ci.yml
Cargo.toml
arci-gamepad-gilrs/Cargo.toml
arci-gamepad-gilrs/src/lib.rs
openrr-apps/schema/robot_config.json
openrr-apps/schema/robot_teleop_config.json

This allows CI to ensure that the schema is up-to-date. Resolves the following todo:
https://github.com/openrr/openrr/blob/5fd3193f2ddb66d9ec48abd6fbeedec7443e7b76/.github/workflows/ci.yml#L178-L181

Make schema output deterministic

---

.github/.cspell/project-dictionary.txt
Cargo.toml
arci-ros2/src/navigation.rs
arci-ros2/src/ros2_control.rs
openrr-plugin/Cargo.toml
openrr-plugin/src/gen/api.rs
openrr-plugin/src/gen/proxy.rs
openrr-plugin/src/lib.rs
openrr-plugin/src/proxy.rs
tools/codegen/src/plugin.rs

Part of #870 (fix it by combining this with #863)
- Removes async -> blocking -> async translation.
- Improve codegen to support JointTrajectoryClient/Gamepad.

[openrr-plugin] Handle futures efficiently

---

openrr-apps/Cargo.toml
openrr-client/Cargo.toml
openrr-command/Cargo.toml
openrr-gui/Cargo.toml
openrr-planner/Cargo.toml
openrr-teleop/Cargo.toml
openrr/Cargo.toml

~~Depends on #897. (The first and second commits are from it)~~
If there are no problems (or even if there are problems, they are fixed) I plan to eventually remove the dependence on assimp.
cc #148

Make assimp feature disabled by default

---

.deny.toml
arci-gamepad-gilrs/examples/gilrs_check_keymap.rs
arci-gamepad-gilrs/src/lib.rs
openrr-apps/schema/robot_teleop_config.json

Add new method to send command avoid using event handler.

[arci-gamepad-gilrs] Update send command process

---

ci/ubuntu-setup-lld.sh
openrr-apps/src/robot_config.rs
tools/codegen/src/main.rs
tools/codegen/src/plugin.rs
tools/codegen/src/rpc.rs

Fixes newly added clippy warning & Updates lld to fix failure on ubuntu-latest runner that [recently updated to ubuntu-24.04](https://github.com/actions/runner-images/issues/10636).

Fix CI failures

---

.deny.toml
.github/workflows/ci.yml
.markdownlint.yml
Cargo.toml
arci-speak-cmd/src/lib.rs

This reverts commit 0e14e491ed488ad7e5b146829c250de58ebade94.
The rosrust issue has been fixed.

Revert "Apply patch for for xml-rs"

---

arci-ros/src/ros_control/joint_velocity_controller.rs
arci-ros/tests/test_nav_client.rs
openrr-apps/src/bin/robot_command.rs
openrr-planner/src/collision/self_collision_checker.rs
openrr-tracing/examples/influxdb.rs

Fixes new warning in Rust 1.88.

Fix CI failure
