openrr/openrr

Cargo.toml
README.md
openrr-gui/Cargo.toml
openrr-gui/README.md
openrr-gui/examples/joint_position_sender.rs
openrr-gui/src/error.rs
openrr-gui/src/joint_position_sender.rs
openrr-gui/src/lib.rs
openrr-gui/src/style.rs

```rust
/// Launches GUI that send joint positions from GUI to the given `robot_client`.
pub fn joint_position_sender<S, M, N>(
robot_client: RobotClient<S, M, N>, 
urdf: impl AsRef<Path>,
) -> Result<(), Error> { /* ... */ }
pub enum Error { /* ... */ }
```
```rust
use log::debug;
use openrr_apps::RobotConfig;
use openrr_client::BoxRobotClient;
use openrr_gui::joint_position_sender;
use structopt::StructOpt;
#[derive(StructOpt, Debug)]
struct Opt {
config_path: String,
urdf_path: String,
}
fn main() -> anyhow::Result<()> {
env_logger::init();
let opt = Opt::from_args();
debug!("opt: {:?}", opt);
let config = RobotConfig::try_new(&opt.config_path)?;
let client: BoxRobotClient = config.create_robot_client()?;
joint_position_sender(client, opt.urdf_path)?;
Ok(())
}
```
- Launch urdf-viz. …

[openrr-gui] Add openrr-gui

---

arci/src/clients.rs
arci/src/clients/dummy_navigation.rs

This PR adds DummyNavigation struct, which is based on DummyMoveBase struct.

[arci] Create DummyNavigation struct

---

arci-ros/src/error.rs
arci/src/error.rs
openrr-apps/src/error.rs
openrr-client/src/error.rs
openrr-command/src/error.rs
openrr-planner/src/errors.rs

This allows avoiding breakage due to adding new variants.
Refs: https://doc.rust-lang.org/reference/attributes/type_system.html#the-non_exhaustive-attribute

Use #[non_exhaustive] on Error enums

---

arci-urdf-viz/Cargo.toml
arci-urdf-viz/src/client.rs
arci-urdf-viz/tests/test_client.rs

- to avoid multiple spawning of send_joint_positions thread.
- to follow latest target.

[arci-urdf-viz] send_joint_positions in one thread

---

Cargo.toml

arci-ros is included in root workspace since https://github.com/openrr/openrr/commit/08187e454496af17e005a0aa2617c1135519a686.

Remove outdated comment in Cargo.toml

---

openrr-apps/Cargo.toml
openrr-apps/README.md
openrr-apps/src/bin/joint_position_sender.rs
openrr-gui/Cargo.toml
openrr-gui/README.md

This moves the application part of `openrr-gui` to `openrr-apps` as `openrr_apps_joint_position_sender` under the `gui` feature (enabled by default).
Closes #102
- Launch urdf-viz.
```bash
urdf-viz ./openrr-planner/sample.urdf
```
- Launch openrr_apps_joint_position_sender.
```bash
./target/release/openrr_apps_joint_position_sender \
./openrr-apps/config/sample_robot_client_config_for_command_urdf_viz.toml \
./openrr-planner/sample.urdf
```

[openrr-apps, openrr-gui] Move the application part of openrr-gui to openrr-apps

---

Cargo.toml
arci-speak-cmd/Cargo.toml
arci-speak-cmd/LICENSE
arci-speak-cmd/examples/local_command.rs
arci-speak-cmd/src/lib.rs

Closes #119
```rust
/// A [`Speaker`] implementation using a local command.
///
/// Currently, this uses the following command:
///
/// - On macOS, use `say` command.
/// - On Windows, call [SAPI] via PowerShell.
/// - On others, use `espeak` command.
///
/// **Disclaimer**: These command might change over time.
///
/// [SAPI]: https://en.wikipedia.org/wiki/Microsoft_Speech_API
#[derive(Debug, Default)]
pub struct LocalCommand { /* ... */ }
impl LocalCommand {
/// Creates a new `LocalCommand`.
pub fn new() -> Self { /* ... */ }
/// Similar to `Speaker::speak`, but returns an error when the command failed.
pub fn try_speak(&self, message: &str) -> io::Result<()> { /* ... */ }
}
impl Speaker for LocalCommand { /* ... */ }
```
```rust
use arci::Speaker;
use arci_speak_cmd::LocalCommand;
use …
```

[arci-speak-cmd] Add arci-speak-cmd

---

arci/src/waits.rs

Closes #108
Before this change, if the timeout was 10 sec,
the smallest wait rate was 1 Hz (10 / 10 = 1).
It means that even if the sent trajectory was very short (like 10msec),
it waits 1sec at least.
By this change the unit duration is set to 10msec.
(I'm not sure that it is enough small (can be 1msec, but it increase the cost))
It means the smallest sleep is 10 msec always, and nothing to
do with the timeout sec now.

[arci] Change the wait logic

---

arci-gamepad-gilrs/Cargo.toml
arci-ros/Cargo.toml
arci-speak-cmd/Cargo.toml
arci-urdf-viz/Cargo.toml
openrr-apps/Cargo.toml
openrr-client/Cargo.toml
openrr-command/Cargo.toml
openrr-gui/Cargo.toml
openrr-teleop/Cargo.toml
openrr/Cargo.toml

Because root Cargo.toml patches the paths, we don't need relative paths
Refs #137

Stop to use relative path for inside crates

---

arci-ros/build.rs

This old hack causes error on cargo install.

[arci-ros] Stop to use parent() -> arci-ros to search msg files

---

openrr-planner/src/collision/collision_checker.rs

k::Chain is thread same, and sometimes bellow error happens.
I hope this improve the situation.
thread '<unnamed>' panicked at 'cache must exist', /Users/ogura/.cargo/registry/src/github.com-1ecc6299db9ec823/k-0.22.1/src/chain.rs:383:70
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /Users/ogura/rust/openrr/openrr-planner/src/collision/collision_checker.rs:177:54

call update before collision check

---

arci-speak-cmd/Cargo.toml

It should have been 0.0.1, but v0.1.0 is released.
When we release v0.1.0, we have to skip v0.1.0
for arci-speak-cmd.

[arci-speak-cmd] v0.1.0 -> v0.0.3

---

openrr-apps/src/robot_config.rs

This was a side effect of making ros feature as a default.

[openrr-apps] Fix clippy warning

---

.github/workflows/coverage.yaml
.github/workflows/main.yml
.github/workflows/ros1.yaml
ci/ubuntu-install-dependencies.sh

If we forget to update the dependency installation command for the Linux environment, #206 will break easily. And it's hard to notice until the release process actually started.
This patch separates the dependency installation commands into scripts for easier management. Also, this makes workflows that aren't run regularly like #206 hard to break.

[workflows] Separate the dependency installation on linux into a script

---

openrr-gui/src/joint_position_sender.rs
openrr-gui/src/style.rs

cc https://github.com/openrr/openrr/issues/101

[openrr-gui] Add text input to set duration and improve error handling about text input

---

openrr-gui/Cargo.toml

zerocopy 0.3.1 removed support for stable Rust. We want to use stable, so pin zerocopy to 0.3.0. 
zerocopy 0.3.1 depends on min_const_generics that requires 1.51.0 (the current beta, [it will be released as stable in 2021-03-25](https://github.com/rust-lang/rust/blob/relnotes-1.51.0/RELEASES.md#version-1510-2021-03-25)).
Therefore, it cannot be used in the current stable (1.50.0). 
https://github.com/openrr/openrr/runs/2036728847?check_suite_focus=true
> ```
> error[E0658]: const generics are unstable
>    --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/zerocopy-0.3.1/src/lib.rs:71:38
>     |
> 71  |         unsafe impl<T: $trait, const N: usize> $trait for [T; N] {
>     |                                      ^
> ...
> 263 | impl_for_composite_types!(FromBytes);
>     | …
```

[openrr-gui] Pin zerocopy to 0.3.0

---

openrr-gui/Cargo.toml

This reverts commit 2d29c13ce25ef2897c828b011e3c441f27d71577 (#216).

[openrr-gui] Revert "Pin zerocopy to 0.3.0"

---

openrr-client/src/robot_client.rs

I think it makes sense to implement Default, as all fields can be omitted when deserializing.

[openrr-client] impl Default for OpenrrClientsConfig

---

openrr-client/Cargo.toml
openrr-client/src/clients.rs
openrr-client/src/clients/local_move.rs
openrr-client/src/error.rs
openrr-client/tests/local_move_sample.toml

This PR adds a struct to move robots to a goal directly.
The placement of the sample configuration file named `local_move_sample.toml`, which is used for tests, should be discussed.

[openrr-client] Add LocalMove

---

.github/workflows/main.yml
.github/workflows/release.yml
ci/publish.sh

The workflow added by this patch launches when the tag is pushed and does the following:
- Creates a GitHub release.
- Publishes the crates listed in ci/publish.sh to crates.io.
See openrr/urdf-viz#44 for more.
Closes #154

[workflows] Automate release process

---

ci/publish.sh

Fixes release workflow.
https://github.com/openrr/openrr/runs/2216239543?check_suite_focus=true
> No space left on device

[ci] Run `cargo clean` before `cargo publish`

---

arci/src/clients/dummy_navigation.rs
openrr-client/src/clients/local_move.rs

```console
$ cargo clippy --all-targets
error: strict comparison of `f32` or `f64`
--> openrr-client/src/clients/local_move.rs:139:9
|
139 |         assert_eq!(vel0.x, 1.0); // linear_gain = 1.0
|         ^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[deny(clippy::float_cmp)]` on by default
= note: `f32::EPSILON` and `f64::EPSILON` are available for the `error_margin`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#float_cmp
= note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

Use assert_approx_eq for float comparison

---

arci-urdf-viz/tests/test_client.rs
arci-urdf-viz/tests/test_web.rs
arci-urdf-viz/tests/web_server.rs

reduce boilerplate code
```diff
- std::thread::spawn(move || web_server.start());
- std::thread::sleep(std::time::Duration::from_secs(1));
+ web_server.start_background();
```

[arci-urdf-viz] Add start_background method to mock server

---

openrr-gui/src/joint_position_sender.rs

The position specified by the slider is guaranteed to be in range, but it may actually be out of range because the value is rounded.
So, if the position is out of the range, handle it as the same value as the limit.

[openrr-gui] Do not send position that out of the range

---

openrr-apps/Cargo.toml
openrr-apps/README.md
openrr-gui/Cargo.toml
openrr-gui/README.md

[The troubleshooting doc](https://github.com/openrr/openrr/tree/main/openrr-gui#troubleshooting) mentions iced/glow feature, but its feature is not selectable when installing openrr-apps because iced is not a dependency of openrr-apps.

[openrr-gui, openrr-apps] Add glow feature

---

openrr-apps/Cargo.toml
openrr-planner/Cargo.toml

Since 1.46, cargo can automatically detect the value of the readme field if readme is in the default location (`readme = "README.md"`).

Remove readme field from Cargo.toml

---

arci-ros/src/ros_nav_client.rs
arci-urdf-viz/Cargo.toml
arci-urdf-viz/src/client.rs
arci-urdf-viz/tests/test_client.rs
arci-urdf-viz/tests/test_web.rs
arci-urdf-viz/tests/web_server.rs
arci/src/clients/dummy_navigation.rs
arci/src/traits/navigation.rs
openrr-client/src/robot_client.rs
openrr-command/src/robot_command.rs

- Change async method `Navigation::move_to` to normal method `send_goal_pose` that return future.
cc #172

Change Navigation::move_to to send_goal_pose

---

arci-urdf-viz/tests/test_client.rs

TotalJointDiffCondition allows error of 0.02, so WaitFuture may complete before the joint reaches the target. So, allow more error than TotalJointDiffCondition allows, when comparison.

[arci-urdf-viz] Fix flaky test

---

openrr-apps/src/bin/robot_command.rs
openrr-apps/src/bin/robot_teleop.rs
openrr-apps/src/error.rs

cc #252
```console
$ target/debug/openrr_apps_robot_command --show-default-config
urdf_viz_clients_total_complete_allowable_error = 0.02
urdf_viz_clients_complete_timeout_sec = 3.0
use_move_base_urdf_viz_web_client = true
use_navigation_urdf_viz_web_client = true
use_localization_urdf_viz_web_client = true
[speak_configs]
[openrr_clients_config]
self_collision_check_pairs = []
[openrr_clients_config.ik_solvers_configs]
```
```console
$ target/debug/openrr_apps_robot_teleop --show-default-config
robot_config_path = ""
initial_mode = ""
[control_nodes_config]
joy_joint_teleop_configs = []
ik_node_teleop_configs = []
[gil_gamepad_config]
device_id = 0
[gil_gamepad_config.map]
button_map = [["LeftTrigger2", "LeftTrigger2"], ["DPadUp", "DPadUp"], ["DPadLeft", "DPadLeft"], ["LeftTrigger", …
```

[openrr-apps] Add flag to show the default setting as TOML

---

openrr-apps/src/bin/joint_position_sender.rs
openrr-client/src/robot_client.rs

Allow removing redundant `.as_ref()` in user side.

[openrr-client] Return Option<&Path> instead of &Option<PathBuf> in OpenrrClientsConfig::urdf_full_path

---

openrr-apps/src/bin/joint_position_sender.rs
openrr-gui/src/error.rs
openrr-gui/src/joint_position_sender.rs

This is useful if the user has not managed urdf as a file. For example, when used in an environment where cannot be access to local files (like wasm), or when urdf is embedded in another file.
~~This PR is marked as a draft because based on #280.~~
See the second and third commit for actual changes in this PR.

[openrr-gui] Take urdf_rs::Robot instead of Path in joint_position_sender

---

arci-ros/src/ros_control_client.rs
arci-urdf-viz/src/client.rs
arci-urdf-viz/tests/test_client.rs
arci/src/clients/joint_position_limiter.rs
arci/src/clients/joint_velocity_limiter.rs

This adds `JointVelocityLimiter::from_urdf` method that creates a new `JointVelocityLimiter` with the velocity limits defined in URDF.

[arci] Add JointVelocityLimiter::from_urdf

---

openrr-client/src/clients/collision_avoid_client.rs
openrr-client/src/clients/collision_check_client.rs
openrr-planner/src/collision/collision_checker.rs

This fixes new clippy warnings added in the latest stable (1.52).
- Fix clippy::filter_map_identity warning
- Fix clippy::manual_map warning
- Fix clippy::inconsistent_struct_constructor warning
```text
error: called `filter_map(|x| x)` on an `Iterator`
--> openrr-planner/src/collision/collision_checker.rs:375:14
|
375 |             .filter_map(|col_tuple| col_tuple)
|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `flatten()`
|
= note: `-D clippy::filter-map-identity` implied by `-D warnings`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#filter_map_identity
error: manual implementation of `Option::map`
--> openrr-planner/src/collision/collision_checker.rs:368:25
|
368 | /                         match …
```

[openrr-planner,openrr-client] Fix clippy warnings added in 1.52

---

.github/workflows/main.yml
.github/workflows/ros1.yaml
Cargo.toml
arci-speak-audio/Cargo.toml
openrr-apps/Cargo.toml
openrr-apps/README.md
openrr-client/Cargo.toml
openrr-command/Cargo.toml
openrr-gui/Cargo.toml
openrr-teleop/Cargo.toml
openrr/Cargo.toml

Both or either is not available on some platforms, which can be a problem when working on support for platforms like WASM.
This PR makes both dependencies optional features.
This also adds a CI task that checks all feature combinations work properly.

Make dependency on assimp and mio optional

---

openrr-apps/src/bin/robot_command.rs
openrr-apps/src/bin/robot_teleop.rs

structopt recognizes the doc comment and treats it as a help message.

[openrr-apps] Use doc comments instead of #[structopt(about)]

---

arci/src/waits.rs

Hopefully, this will make 100% test coverage for this file.
https://codecov.io/gh/openrr/openrr/src/main/arci/src/waits.rs

[arci] Use WaitFuture::from in WaitFuture::new

---

.github/workflows/coverage.yaml
.github/workflows/main.yml
.github/workflows/ros2.yaml
Cargo.toml
arci-ros2/Cargo.toml
arci-ros2/LICENSE
arci-ros2/README.md
arci-ros2/examples/cmd_vel.rs
arci-ros2/src/cmd_vel_move_base.rs
arci-ros2/src/lib.rs
arci-ros2/tests/test_cmd_vel.rs

It requires ROS2 Foxy (Ubuntu 20.04).
* r2r is not published to crates.io yet.
* It requires ROS2 foxy is installed.

[arci-ros2] Add arci-ros2 (only MoveBase trait)

---

Cargo.toml
arci-gamepad-gilrs/src/lib.rs
arci-ros/src/cmd_vel_move_base.rs
arci-ros/src/ros_control_client.rs
arci-ros/src/ros_localization_client.rs
arci-ros/src/ros_nav_client.rs
arci-ros/src/ros_speak_client.rs
arci-urdf-viz/src/client.rs
ci/publish.sh
openrr-apps/Cargo.toml
openrr-apps/README.md
openrr-apps/src/bin/config.rs
openrr-apps/src/bin/joint_position_sender.rs
openrr-apps/src/bin/robot_command.rs
openrr-apps/src/bin/robot_teleop.rs
openrr-apps/src/robot_config.rs
openrr-apps/src/robot_teleop_config.rs
openrr-client/src/clients/collision_check_client.rs
openrr-client/src/clients/ik_client.rs
openrr-client/src/clients/local_move.rs
openrr-client/src/robot_client.rs
openrr-config/Cargo.toml
openrr-config/LICENSE
openrr-config/README.md
openrr-config/src/lib.rs
openrr-teleop/src/control_nodes_config.rs
openrr-teleop/src/ik.rs
openrr-teleop/src/joints.rs
openrr-teleop/src/joints_pose_sender.rs

Closes #78 Closes #165
- overwrite default values by argument (`--config` flag. `--teleop-config`/`--robot-config` flag  in openrr_apps_robot_teleop.)
- overwrite default values by another toml file (`openrr_apps_config merge`)
By using `--config` flag, you can overwrite the configuration at startup.
For example, to replace the urdf path:
```bash
openrr_apps_robot_command \
--config-path=./openrr-apps/config/sample_robot_client_config_for_urdf_viz.toml \
--config='openrr_clients_config.urdf_path="path/to/urdf"' \
load_commands ./openrr-apps/command/sample_cmd_urdf_viz.txt
```
In `openrr_apps_robot_teleop`, there are two flags: `--robot-config` to overwrite robot config and `--teleop-config` to overwrite teleop config.
For example, to run `openrr_apps_robot_teleop` with …

[openrr-apps,openrr-config] Support overwriting config

---

arci/Cargo.toml
arci/src/clients.rs
arci/src/clients/lazy.rs
arci/src/error.rs
openrr-apps/src/robot_config.rs

This makes the creation of clients except for arci-ros's JointTrajectoryClient lazy.
before:
```console
$ urdf-viz ./openrr-planner/sample.urdf &
$ RUST_LOG=openrr_apps=debug cargo run -p openrr-apps --bin openrr_apps_joint_position_sender -- --config-path ./openrr-apps/config/sample_robot_client_config_for_urdf_viz.toml
May 21 17:10:58.516 DEBUG openrr_apps_joint_position_sender: opt: Opt { ... }
May 21 17:10:58.519 DEBUG openrr_apps::robot_config: RobotConfig { ... }
May 21 17:10:58.519 DEBUG openrr_apps::utils: init openrr_apps_joint_position_sender with RobotConfig { ... }
May 21 17:10:58.520 DEBUG create_print_speaker: openrr_apps::robot_config: creating PrintSpeaker
May 21 17:10:58.537 DEBUG create_localization_with_ros:create_localization_without_ros: openrr_apps::robot_config: …
```

[openrr-apps] Create clients lazily

---

arci-urdf-viz/src/client.rs
arci-urdf-viz/tests/test_client.rs
arci-urdf-viz/tests/test_web.rs
openrr-apps/src/robot_config.rs

The thread has a cloned `Arc`, so this drop will never be called and `is_dropping` flag will never set to `true`.
https://github.com/openrr/openrr/blob/36a3e59b2f6dcf9c8faa281fbd77783fd6531706/arci-urdf-viz/src/client.rs#L315-L319
And the thread will not terminate unless `is_dropping` flag is `true`.
https://github.com/openrr/openrr/blob/36a3e59b2f6dcf9c8faa281fbd77783fd6531706/arci-urdf-viz/src/client.rs#L244
Therefore, the thread and `Arc<UrdfVizWebClientInner>` will continue to live until the end of the program even if the client is dropped.

[arci-urdf-viz] Fix leak

---

arci-urdf-viz/tests/web_server.rs

Currently, the default value of `RobotOrigin::quaternion` is `[0.0,0.0,0.0,0.0]`.
https://github.com/openrr/openrr/blob/fe3494605ed2e9131d45741a8ad077588a54001a/arci-urdf-viz/tests/web_server.rs#L22-L26
However, if quaternion is `[0.0,0.0,0.0,0.0]`, this conversion will fail ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9406215f3a35be566969900401cc1062)).
https://github.com/openrr/openrr/blob/fe3494605ed2e9131d45741a8ad077588a54001a/arci-urdf-viz/src/utils.rs#L88-L90
And this request will fail due to the conversion failure. (If the conversion fails, some values of the `pose` will be nan.)
https://github.com/openrr/openrr/blob/fe3494605ed2e9131d45741a8ad077588a54001a/arci-urdf-viz/src/client.rs#L254
`urdf_viz::Data` also uses the same default value, …

[arci-urdf-viz] Fix default value of quaternion in web server

---

.github/dependabot.yml

These dependencies need to be updated at the same time.

Ignore dependabot update of nalgebra, ncollide3d, k, and urdf-viz

---

.github/workflows/coverage.yaml
arci-ros2/Cargo.toml
arci-ros2/src/cmd_vel_move_base.rs
arci-ros2/src/lib.rs
arci-ros2/src/plugin.rs
openrr-apps/config/sample_robot_client_config_for_plugin.toml

~~Depend on #319~~
```sh
cargo build -p arci-ros2 --features ros2
cargo build -p openrr-plugin-example
gazebo --verbose /opt/ros/foxy/share/gazebo_plugins/worlds/gazebo_ros_diff_drive_demo.world
cargo run -p openrr-apps --bin openrr_apps_velocity_sender -- \
--config-path ./openrr-apps/config/sample_robot_client_config_for_plugin.toml \
--config='move_base="arci_ros2";plugins.arci_ros2.instances[0].args="topic=\"/demo/cmd_demo\""'
```

[arci-ros2] Allow arci-ros2 to be used as plugin

---

arci-ros2/Cargo.toml
arci-ros2/src/plugin.rs

`r2r::Node` is now `Send`. https://github.com/sequenceplanner/r2r/commit/5ab5ab5e3f5f0f137886fd98654b6e7cc99ea3b1

[arci-ros2] Store Node globally

---

openrr-apps/src/bin/config.rs
openrr-apps/src/bin/joint_position_sender.rs
openrr-apps/src/bin/robot_command.rs
openrr-apps/src/bin/robot_teleop.rs
openrr-apps/src/bin/velocity_sender.rs
openrr-apps/src/utils.rs
tools/update-schema.sh

openrr_apps_config uses stdout, so if we use stdout for output of log, it will conflicts.

[openrr-apps] Emit log to stderr instead of stdout

---

arci-gamepad-gilrs/src/lib.rs
arci-gamepad-keyboard/src/lib.rs
arci-ros/src/lib.rs
arci-ros2/src/lib.rs
arci-speak-audio/src/lib.rs
arci-speak-cmd/src/lib.rs
arci-urdf-viz/src/lib.rs
arci/src/lib.rs
openrr-apps/src/lib.rs
openrr-client/src/lib.rs
openrr-command/src/lib.rs
openrr-config/src/lib.rs
openrr-gui/src/lib.rs
openrr-planner/src/lib.rs
openrr-plugin/src/lib.rs
openrr-sleep/src/lib.rs
openrr-teleop/src/lib.rs
openrr-teleop/src/switcher.rs
openrr/src/lib.rs

In the current implementation, if the index is loaded while increment_mode is being processed, the index may point out of range.
I guess this is a bug introduced by clippy::mutex_atomic lint's false positive was misinterpreted as a correct warning. I think it is possible to write this using atomic, but it is more complicated because it requires a way like CAS loop.

[openrr-teleop] Fix panic in switcher

---

openrr-client/src/clients/collision_avoidance_client.rs

Since `planner` field has the same chain.
https://github.com/openrr/openrr/blob/04a02bef8ef2e027eccb43995960d55a2641a2b9/openrr-planner/src/planner/joint_path_planner.rs#L31

[openrr-client] Remove a robot field from CollisionAvoidanceClient

---

arci-urdf-viz/src/client.rs
arci-urdf-viz/src/utils.rs
arci/src/error.rs
openrr-apps/config/sample_robot_client_config_for_urdf_viz_minimal.toml
openrr-apps/src/bin/joint_position_sender.rs
openrr-apps/src/bin/robot_command.rs
openrr-apps/src/bin/robot_teleop.rs
openrr-apps/src/bin/velocity_sender.rs
openrr-apps/src/error.rs
openrr-apps/src/robot_teleop_config.rs
openrr-teleop/src/control_nodes_config.rs

Depend on https://github.com/openrr/urdf-viz/pull/96.
```sh
cargo run --manifest-path ../urdf-viz/Cargo.toml -- ./openrr-planner/sample.urdf &
cargo run -p openrr-apps --bin openrr_apps_joint_position_sender
cargo run -p openrr-apps --bin openrr_apps_robot_teleop
```

Support urdf-viz client without config

---

openrr-client/src/clients/collision_check_client.rs
openrr-planner/src/collision/self_collision_checker.rs

A robot defined in `sample.urdf` has only 8 movable joints. This PR corrects mistakes I made in #396 and #407  .

[planner & client] Correct DoF in collision check tests

---

openrr-planner/src/planner/joint_path_planner.rs

In current implementation, both `plan()` and `plan_avoid_self_collision()` functions never show which links will collide, since resetting joint angles runs before identify the link names.
This PR solves this problem just by inverting algorithms: first, get collision link names with reference joint angles; then, reset joint angles.

[openrr-planner] Get collision link names before resetting

---

openrr-planner/src/collision/self_collision_checker.rs
openrr-planner/src/errors.rs
openrr-planner/src/planner/joint_path_planner.rs

`CollisionPart` is not a good name and sometimes confuses us: e.g. the name reminds us NOT a trajectory point BUT a LINK colliding with itself or environments.

[openrr-planner] Rename enum describing trajectory invalidity

---

openrr-client/src/clients/collision_check_client.rs
openrr-client/src/robot_client.rs
openrr-planner/src/collision/self_collision_checker.rs

SelfCollisionChecker is similar to JointPathPlaner, and we start to create a new struct describing common parameters of them.
As the first step of the challenge, this PR introduces generics in SelfCollisionChecker as used in JointPathPlanner.
Reference:
https://github.com/openrr/openrr/blob/52af54eaf69ad0b9152dd2d1e6000dd36c7e85a9/openrr-planner/src/planner/joint_path_planner.rs#L25-L390

[planner] Use generics in SelfCollisionChecker refering to JointPathPlanner

---

openrr-client/src/clients/collision_avoidance_client.rs
openrr-planner/examples/reach.rs
openrr-planner/src/collision.rs
openrr-planner/src/collision/collision_detector.rs
openrr-planner/src/collision/self_collision_checker.rs
openrr-planner/src/lib.rs
openrr-planner/src/planner/joint_path_planner.rs

After this change, 'check' becomes a term only used in contexts of planning.
I note that this PR does not include functional changes nor effects on our private repos.

Rename CollisionChecker into CollisionDetector to prevent misleading

---

openrr-client/src/clients/collision_check_client.rs
openrr-planner/src/collision/self_collision_checker.rs

Change the structures of `SelfCollisionChecker` and `CollisionCheckClient` by referring to those of `JointPathPlanner` and `CollisionAvoidanceClient`, which are shown below.
https://github.com/openrr/openrr/blob/b9688c220d6d82338da43ee064c0b0228b7e98a6/openrr-client/src/clients/collision_avoidance_client.rs#L23-L31

Move using_joints from SelfCollisionChecker to CollisionCheckerClient

---

openrr-planner/src/collision/collision_detector.rs

The removed member would never be used here.
Instead, `self_collision_check_pairs` is introduced in RobotCollisionDetector with a robot model, as I proposed in #444 .

[openrr-planner] Remove a unused member from CollisionDetector

---

openrr-planner/src/collision.rs
openrr-planner/src/collision/robot_collision_detector.rs

Currently `JointPathPlanner` and `SelfCollisionChecker` have same members for collision checking.
This PR introduces `RobotCollisionDetector` struct extracting the common members and wrap collision detection processes with a robot model. This struct will be embedded in them in another PR.
References: 
- [JointPathPlanner](https://github.com/openrr/openrr/blob/main/openrr-planner/src/planner/joint_path_planner.rs)
- [SelfCollisionChecker](https://github.com/openrr/openrr/blob/main/openrr-planner/src/collision/self_collision_checker.rs)
~This PR opens after #443 is merged.~

[openrr-planner] Create RobotCollisionDetector

---

openrr-planner/src/planner/joint_path_planner.rs

https://github.com/openrr/openrr/blob/d6971f240cb9fc5fd3a84da9a43dfbe8c222be8b/openrr-planner/src/planner/joint_path_planner.rs#L288-L290
https://github.com/openrr/openrr/blob/d6971f240cb9fc5fd3a84da9a43dfbe8c222be8b/openrr-planner/src/planner/joint_path_planner.rs#L352-L354
As shown above, there exist two same `impl` blocks in succession. This PR just resolves the duplication.

[openrr-planner] Refactor impl blocks of JointPathPlannerBuilder

---

openrr-planner/examples/reach.rs
openrr-planner/src/planner/ik_planner.rs
openrr-planner/src/planner/joint_path_planner.rs

The removed member variable `urdf_robot` is no longer used since collision_check_robot already exists.
This PR does not affect any other packages.

[openrr-planner] Remove urdf_robot from JointPathPlanner

---

openrr-planner/src/collision/robot_collision_detector.rs

The purpose is to unify the argumentss of `create_*` functions.
E.g. 
https://github.com/openrr/openrr/blob/d6971f240cb9fc5fd3a84da9a43dfbe8c222be8b/openrr-planner/src/collision/self_collision_checker.rs#L158-L163

[openrr-planner] Separate a URDF path from RobotCollisionDetectorConfig

---

openrr-client/src/clients/collision_avoidance_client.rs
openrr-planner/examples/reach.rs
openrr-planner/src/planner/ik_planner.rs
openrr-planner/src/planner/joint_path_planner.rs

JointPathPlanner ver. of the PR #457 .
Note that the removed functions were moved to RobotCollisionDetector.

[openrr-planner] Use RobotCollisionDetector in JointPathPlanner

---

arci-speak-audio/Cargo.toml

This reverts commit 89bf3ad3e7e2ee5c710e01fe4ce86831dc562359.
alsa 0.5.1 has been yanked, so we no longer need to pin it.

Revert "[arci-speak-audio] pin alsa to 0.5.0"

---

openrr-planner/src/planner/joint_path_planner.rs

Currently the function named `get_joint_path_planner_builder_from_urdf` just wraps `JointPathPlannerBuilder::new` redundantly. Therefore this PR resolves the redundancy by removing the former.
(If there exists any reason to keep it, please let me know.)

[openrr-planner] Remove a duplicated function

---

openrr-planner/src/collision/collision_detector.rs
openrr-planner/src/planner/joint_path_planner.rs

A test focusing on CollisionDetector functions has existed in `openrr-planner/src/planner/joint_path_planner.rs` since the start of openrr project. This PR just moves the test to the suitable file, i.e. `openrr-planner/src/collision/collision_detector.rs`.

[openrr-planner] Move a test of CollisionDetector to the suitable file

---

arci-gamepad-gilrs/Cargo.toml
arci-gamepad-keyboard/Cargo.toml
arci-ros/Cargo.toml
arci-ros2/Cargo.toml
arci-speak-audio/Cargo.toml
arci-speak-cmd/Cargo.toml
arci-urdf-viz/Cargo.toml
arci/Cargo.toml
openrr-apps/Cargo.toml
openrr-client/Cargo.toml
openrr-command/Cargo.toml
openrr-config/Cargo.toml
openrr-gui/Cargo.toml
openrr-planner/Cargo.toml
openrr-plugin/Cargo.toml
openrr-plugin/examples/plugin/Cargo.toml
openrr-remote/Cargo.toml
openrr-sleep/Cargo.toml
openrr-teleop/Cargo.toml
openrr/Cargo.toml

This field is soft-deprecated, cargo no longer generates this field by default, and Rust's official services no longer reference this field at all.
See [RFC3052](https://rust-lang.github.io/rfcs/3052-optional-authors-field.html) for more.

Remove authors field from Cargo.toml

---

arci-ros2/src/plugin.rs
openrr-plugin/benches/proxy.rs
openrr-plugin/examples/load_plugin.rs
openrr-plugin/examples/plugin/src/lib.rs
openrr-plugin/src/gen/api.rs
openrr-plugin/src/gen/proxy.rs
openrr-plugin/src/lib.rs
tools/codegen/src/plugin.rs

Since the name of the plugin is specified by config, this method is currently unused.
https://github.com/openrr/openrr/blob/bc5d4e50636c1eba6ff1243a11e1644c036ab51e/openrr-apps/config/sample_robot_client_config_for_plugin.toml#L55
Considering that the name is not a unique identifier and we can get the package name from the plugin filename, I think it is unlikely that this will actually be needed in the future.

[openrr-plugin] Remove Plugin::name method

---

.github/actions/spelling/expect.txt
.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/release.yml
arci-gamepad-gilrs/src/lib.rs

```text
warning: variable does not need to be mutable
--> arci-gamepad-gilrs/src/lib.rs:229:17
|
229 |             let mut selected_gamepad_id = None;
|                 ----^^^^^^^^^^^^^^^^^^^
|                 |
|                 help: remove this `mut`
|
= note: `#[warn(unused_mut)]` on by default
```

[arci-gamepad-gilrs] Fix unused_mut warning on macOS

---

arci-ros/tests/test_rosrust_utils.rs
arci-urdf-viz/tests/test_client.rs

Closes #527
This also marks test_convert_system_time_to_ros_time test as flaky: https://github.com/openrr/openrr/runs/4308736017?check_suite_focus=true

[arci-urdf-viz] Mark test_send_joint_positions test as flaky

---

Cargo.toml
arci-ros/src/lib.rs
arci-ros/src/ros_control/ros_control_action_client.rs
arci-ros/src/ros_nav_client.rs
arci-ros/src/rosrust_utils.rs
arci-ros/tests/hygiene/Cargo.toml
arci-ros/tests/hygiene/src/lib.rs

- Users no longer need to add parking_lot, past, and rosrust as dependencies to use this macro.
- Remove define_action_client_internal and define_action_client_with_namespace macros (merged to define_action_client macro).
- Add a test to check if the macro depends on another crate.

[arci-ros] Clean up define_action_client macro

---

.clippy.toml
.github/workflows/ci.yml
arci-ros/src/lib.rs
arci-ros/src/rosrust_utils.rs

~~Depend on #529~~
`std::sync::mpsc` is buggy and slow. Recommended alternatives are faster `crossbeam-channel` or `flume`.
We are already using `flume` in some crates (https://github.com/openrr/openrr/pull/250), so this patch replaces the remaining use of `std::sync::mpsc` with `flume`.

[arci-ros] Use flume instead of std::sync::mpsc

---

openrr-client/src/clients/ik_client.rs

- velocities must be set in lower level layers.

[openrr-client] Stop setting velocities in IkClient

---

openrr-planner/examples/reach.rs

This PR resolves a bug generated by #453 . Sorry for inconvenience.
We should use `urdf_rs::utils::read_urdf_or_xacro()` instead of `urdf_rs::read_file()`, in order to accept not only raw-urdf files but also xacro files.

[openrr-planner] Fix to read a xacro file in an example

---

openrr-planner/examples/reach.rs

If the zero angle is not included in the limits, the example
does not works. This change improve that behavior.

[openrr-planner] Use clamped() to avoid unwrap() in examples/reach.rs

---

.github/actions/spelling/expect.txt
.github/workflows/ci.yml
.github/workflows/coverage.yml
README.md
arci-ros2/README.md
arci-ros2/examples/ros2_control.rs
arci-ros2/src/lib.rs
arci-ros2/src/navigation.rs
arci-ros2/src/plugin.rs
arci-ros2/src/ros2_control.rs
arci-ros2/src/utils.rs
arci-ros2/tests/test_ros2_control.rs

1\. Install ros2-control and ros2-controllers.
```sh
sudo apt install ros-$ROS2_DISTRO-ros2-control ros-$ROS2_DISTRO-ros2-controllers
```
2\. Clone and build https://github.com/ros-controls/ros2_control_demos
- if ROS2_DISTRO is foxy: checkout foxy branch, install it, and source install/setup.bash.
- if ROS2_DISTRO is galactic: replace all "foxy" in the repository with "galactic", install it, and source install/setup.bash.
3\. Launch rrbot example.
```sh
ros2 launch ros2_control_demo_bringup rrbot.launch.py
```
4\. Stop existing controllers.
```sh
ros2 control set_controller_state joint_state_broadcaster stop
ros2 control set_controller_state forward_position_controller stop
```
5\. Start position_trajectory_controller and joint_state_broadcaster.
```sh
ros2 control load_controller …
```

[arci-ros2] Add Ros2ControlClient

---

.clippy.toml
.github/workflows/ci.yml

similar to https://github.com/openrr/openrr/pull/560, but for clippy::disallowed_types.

Update .clippy.toml to include disallowed reasons (disallowed-types)

---

.github/workflows/ci.yml
.github/workflows/coverage.yml

Use [taiki-e/install-action](https://github.com/taiki-e/install-action) to install prebuilt binaries. This makes the installation faster and may avoid the impact of [problems caused by upstream changes](https://github.com/tokio-rs/bytes/issues/506).

Make installation of cargo-hack & cargo-llvm-cov faster and robust

---

Cargo.toml

At least when the workspace root is a virtual manifest, resolver = "2" does not seem to properly apply in the workspace, even if all workspace members are 2021 edition.
This issue was originally reported in one of our private projects.
https://github.com/taiki-e/cargo-hack/issues/15#issuecomment-1056937385

Re-add resolver = "2"

---

.github/workflows/coverage.yml

LLVM source-based code coverage has been stabilized on Rust 1.60 (currently beta).

Use beta for code coverage

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
openrr-gui/src/velocity_sender.rs

- clippy::disallowed_methods/clippy::disallowed_types are now warned by default
- source-based code coverage has been stabilized
- --check is now a flag of cargo fmt subcommand
The last change was actually made in a bit earlier version.

Update CI for Rust 1.60

---

.github/workflows/ci.yml

This has been failing to build for several days.

Temporarily disable ROS2 galactic in CI

---

arci-speak-audio/Cargo.toml
arci-speak-cmd/Cargo.toml
openrr-apps/Cargo.toml
openrr-command/Cargo.toml
openrr-planner/Cargo.toml
openrr-teleop/Cargo.toml

This reverts commit 648a33f792669178ef884e5ab158164895d24168.
See https://github.com/openrr/openrr/pull/618#discussion_r898131417

Revert "Pin clap to ~3.1"

---

openrr-planner/Cargo.toml
openrr-planner/benches/self_collision_detection.rs

This PR adds a benchmark to evaluate self-collision checking from from the viewpoint of computational time.
---
This PR will open after #612 is merged.

[openrr-planner] Add a benchmark to evaluate self-collision checking

---

.github/actions/spelling/expect.txt
openrr-planner/src/collision/collision_detector.rs

This PR implements a sweep and prune algorithm with AABB (Axis Aligned Bounding Box), in order to accelerate self-collision checking. This implementation is based on bounding volume trees provided by ncollide3d (see https://www.ncollide.org/bounding_volumes/#spacial-partitioning ).
We can evaluate the improvement in computational time with `cargo bench`.
The results in my environment are as follows:
```
[Before]
bench_check_self_collisions                        
time:   [4.6853 ms 4.7762 ms 4.8687 ms]
[After (this PR is applied)]
bench_check_self_collisions                        
time:   [177.70 us 179.92 us 182.28 us]
change: [-96.318% -96.233% -96.146%] (p = 0.00 < 0.05)
Performance has improved.
```

[openrr-planner] Use AABB-based pruning in self-collision checking

---

.github/workflows/ci.yml
Cargo.toml

before (x86_64 macos)
```
5477376 ../target/release/openrr_apps_config
20543392 ../target/release/openrr_apps_joint_position_sender
16224728 ../target/release/openrr_apps_robot_command
17416240 ../target/release/openrr_apps_robot_teleop
20423520 ../target/release/openrr_apps_velocity_sender
```
after (x86_64 macos)
```
2914592 ../target/release/openrr_apps_config
12270000 ../target/release/openrr_apps_joint_position_sender
9764920 ../target/release/openrr_apps_robot_command
10524688 ../target/release/openrr_apps_robot_teleop
12204144 ../target/release/openrr_apps_velocity_sender
```
refs:
- https://doc.rust-lang.org/cargo/reference/profiles.html
- https://github.com/johnthagen/min-sized-rust

Add profile to reduce binary size in release mode

---

openrr-planner/Cargo.toml
openrr-planner/benches/collision_detection.rs

This PR adds a benchmark to evaluate environmental-collision checking from the viewpoint of computational time, as same as #613 .

[openrr-planner] Add a benchmark to evaluate environmental collision checking

---

openrr-planner/src/collision/collision_detector.rs

This PR corrects the mistake in #630 : if there is no potential conflict in each for-loop, the procedure need to go to the next loop. 
Instead of replacing `break` into `continue`, this PR removes `break`, since it lies on the last part of the loop.

[openrr-planner] Fix a self-collision checking algorithm

---

arci-gamepad-gilrs/src/lib.rs
arci-gamepad-keyboard/src/lib.rs
arci-ros/src/lib.rs
arci-ros2/src/lib.rs
arci-speak-audio/src/lib.rs
arci-speak-cmd/src/lib.rs
arci-urdf-viz/src/lib.rs
arci/src/lib.rs
openrr-apps/src/lib.rs
openrr-client/src/lib.rs
openrr-command/src/lib.rs
openrr-config/src/lib.rs
openrr-gui/src/lib.rs
openrr-planner/src/lib.rs
openrr-plugin/src/lib.rs
openrr-remote/src/lib.rs
openrr-sleep/src/lib.rs
openrr-teleop/src/lib.rs
openrr/src/lib.rs

clippy::mutex_atomic has been moved to the allowed by default group in Rust 1.60 (https://github.com/rust-lang/rust-clippy/pull/8260).

Remove unnecessary allowed lints

---

.github/workflows/ci.yml
.github/workflows/spelling.yml

Currently, when the format check of yaml failed, only a warning was displayed and CI did not fail.

Fix format check

---

openrr-command/src/robot_command.rs

This typo is appeared when executing `openrr_apps_robot_command --help`.

[openrr-command] Fix typo

---

openrr-apps/config/sample_robot/sample_robot_speak_audio_sine.txt
openrr-apps/config/sample_robot_client_config_for_urdf_viz.toml
openrr-apps/config/sample_robot_client_config_for_urdf_viz_with_multiple_speaker.toml
openrr-apps/config/sample_teleop_config_urdf_viz_with_multiple_speaker.toml

The other day, the sample model `./openrr-planner/sample.urdf` was updated to twin arm robot. But the sample configs in `openrr-apps` have not updated.

[openrr-apps] Update sample config for twin arm sample model

---

openrr-apps/schema/robot_teleop_config.json

Update openrr-apps/schema/robot_teleop_config.json to support `command_configs` in `ControlNodesConfig` when using EvenBetterToml.

[openrr-apps] Update schema json

---

.github/actions/spelling/expect.txt
openrr-apps/src/bin/joint_position_sender.rs
openrr-apps/src/bin/velocity_sender.rs
openrr-gui/Cargo.toml
openrr-gui/dark_theme.toml
openrr-gui/src/error.rs
openrr-gui/src/joint_position_sender.rs
openrr-gui/src/style.rs
openrr-gui/src/velocity_sender.rs

cc #101
refs: https://github.com/taiki-e/iced_style_config
Resolves the following TODO:
https://github.com/openrr/openrr/blob/1896893a5bed82ae0843188e864f8891054e2ccf/openrr-gui/src/style.rs#L1-L2
It also supports hot reloading of style sheets. This is useful for adjusting styles during development.
https://user-images.githubusercontent.com/43724913/183590429-c81041f6-7ab5-4d6a-be25-4fcf16aa8a20.mov

[openrr-gnu] Use iced_style_config

---

openrr-command/src/robot_command.rs
openrr-planner/src/collision/self_collision_checker.rs

This PR just applies the changes suggested by clippy to deal with the following warnings:
```
warning: deref which would be done by auto-deref
--> openrr-planner/src/collision/self_collision_checker.rs:235:18
|
235 |         .map(|j| (*j).name.to_owned())
|                  ^^^^ help: try this: `j`
|
= note: `#[warn(clippy::explicit_auto_deref)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#explicit_auto_deref
warning: binary comparison to literal `Option::None`
--> openrr-command/src/robot_command.rs:480:20
|
480 |                 && command_parsed_iter.clone().next().unwrap().find('#') == None
|                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use `Option::is_none()` instead: …
```

Apply cargo clippy's warnings

---

.github/workflows/ci.yml

https://github.com/openrr/openrr/runs/8177522904?check_suite_focus=true#logs
```
The following packages have unmet dependencies:
libudev-dev : Depends: libudev1 (= 237-3ubuntu10.53) but 237-3ubuntu10.54 is to be installed
E: Unable to correct problems, you have held broken packages.
```

Fix CI failure on melodic

---

.github/workflows/coverage.yml

Since cargo-llvm-cov [0.5.0](https://github.com/taiki-e/cargo-llvm-cov/releases/tag/v0.5.0), you can omit this.

Remove manual installation of llvm-tools-preview

---

openrr-plugin/src/lib.rs

This is an upstream issue: https://github.com/rodrimati1992/abi_stable_crates/issues/94
```
error: zero-sized fields in repr(transparent) cannot contain external non-exhaustive types
--> openrr-plugin/src/gen/proxy.rs:10:1
|
10 | #[sabi_trait]
| ^^^^^^^^^^^^^
|
= note: `-D repr-transparent-external-private-fields` implied by `-D warnings`
= warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
= note: for more information, see issue #78586 <https://github.com/rust-lang/rust/issues/78586>
= note: this struct contains `UnsafeIgnoredType<SyncSend>`, which contains private fields, and makes it not a breaking change to become non-zero-sized in the future.
= note: this error originates in the attribute macro `sabi_trait` …
```

[openrr-plugin] Ignore repr_transparent_external_private_fields lint

---

openrr-client/src/clients/collision_avoidance_client.rs
openrr-planner/README.md
openrr-planner/examples/minimum.rs
openrr-planner/examples/reach.rs
openrr-planner/src/errors.rs
openrr-planner/src/planner/ik_planner.rs
openrr-planner/src/planner/joint_path_planner.rs

This PR introduces reference_robot to JointPathPlanner in order to make a collision check model independent. Along with this independence, I change to use lists of joint names instead of k::Chain, for planner APIs.
This PR is related to #648 .

[openrr-planner] Change JointPathPlanner APIs

---

openrr-apps/src/bin/robot_command.rs
openrr-apps/src/bin/robot_teleop.rs
openrr-client/src/robot_client.rs
openrr-planner/examples/reach.rs
openrr-plugin/benches/proxy.rs
tools/codegen/src/main.rs

This PR partially resolves #688 , focusing on `clippy::needless_borrow`.

Resolve clippy warnings for needless borrowing

---

.github/workflows/ci.yml

This is currently failing to build: https://github.com/openrr/openrr/actions/runs/3152588967/jobs/5128002998

Temporarily disable ROS2 foxy CI

---

openrr-client/src/clients/collision_avoidance_client.rs
openrr-planner/examples/reach.rs
openrr-planner/src/planner/ik_planner.rs
openrr-planner/src/planner/joint_path_planner.rs

This PR makes robot_collision_detector, a field of JointPathPlanner, private. Along with this visibility change, this PR also adds some APIs to access information the detector only holds.
This PR is related to https://github.com/openrr/openrr/pull/671#discussion_r964365305

[openrr-planner] Capsulize RobotCollisionDetector in JointPathPlanner

---

openrr-planner/Cargo.toml
openrr-planner/src/planner/joint_path_planner.rs

This PR ...
- improves the test coverage
- introduces `flaky_test` to test planning functions using RRTs, which potentially fail

[openrr-planner] Enhance tests for JointPathPlanner

---

openrr-client/src/robot_client.rs
openrr-client/tests/test_robot_client.rs

This PR integrates CollisionAvoidanceClient, a client to use RRT-based planner, into RobotClient.
I am going to update samples in openrr-apps with this change in another PR.

[openrr-client] Integrate CollisionAvoidanceClient to RobotClient

---

openrr-client/src/robot_client.rs
openrr-client/tests/test_robot_client.rs

This PR is a supplement of #697 .
Although the preceding PR tried to integrate JointAvoidanceClient to RobotClient, it missed to register JointAvoidanceClient as JointTrajectoryClient. This PR fixes the mistake and enables JointAvoidanceClient-s to send position commands with planning.

[openrr-client] Correct JointAvoidanceClient registration

---

openrr-client/tests/test_robot_client.rs
openrr-planner/src/collision/self_collision_checker.rs
openrr-planner/src/errors.rs
openrr-planner/src/funcs.rs
openrr-planner/src/planner/joint_path_planner.rs

This PR aims to refactor SelfCollisionChecker with...
- making error information of self-collision checks detailed
- reduce the number of comparison by reversing an order of `match` and `for`

Refactor SelfCollisionChecker

---

arci-ros/Cargo.toml
arci-urdf-viz/Cargo.toml
openrr-apps/Cargo.toml
openrr-client/Cargo.toml
openrr-command/Cargo.toml
openrr-planner/Cargo.toml
openrr-planner/src/collision/collision_detector.rs
openrr-planner/src/collision/robot_collision_detector.rs
openrr-teleop/Cargo.toml

Some tests are fixed because updating `k` changed the order of joints.

Update k requirement from 0.28 to 0.29

---

openrr-apps/command/sample_cmd_urdf_viz.txt
openrr-apps/config/sample_robot_client_config_for_urdf_viz.toml

This PR adds a collision avoidance demo to the openrr-apps main sample.
The following video shows the beginning of the sample: the cross-handed motions (6s-) are generated by JointPathPlanner with self-collision avoidance!
https://user-images.githubusercontent.com/15957608/206153725-65d6abca-f809-40fe-beea-0451b585ebec.mp4

[openrr-apps] Add a collision avoidance demo for sample robot

---

ci/publish.sh
openrr/README.md
openrr/src/lib.rs

openrr:
```
error: couldn't read src/../../README.md: No such file or directory (os error 2)
--> src/lib.rs:1:10
|
1 | #![doc = include_str!("../../README.md")]
|          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)
```
Fixing openrr-remote is somewhat complicated and will not be done in this PR. (see #747 for more)

Fix `cargo publish` errors

---

arci-ros/src/rosrust_utils.rs
arci-urdf-viz/tests/test_client.rs
arci-urdf-viz/tests/test_web.rs
arci/src/clients/dummy_navigation.rs
arci/src/clients/dummy_speaker.rs
arci/src/utils.rs
openrr-apps/src/bin/config.rs
openrr-apps/src/robot_config.rs
openrr-apps/src/robot_teleop_config.rs
openrr-apps/tests/test_robot_config.rs
openrr-apps/tests/test_robot_teleop_config.rs
openrr-client/src/clients/chain_wrapper.rs
openrr-client/src/robot_client.rs
openrr-client/tests/test_robot_client.rs
openrr-gui/src/joint_position_sender.rs
openrr-gui/src/velocity_sender.rs
openrr-planner/src/collision/self_collision_checker.rs
openrr-plugin/benches/proxy.rs
openrr-plugin/examples/plugin/src/lib.rs
openrr-remote/tests/test.rs
openrr-teleop/src/joints.rs
openrr-teleop/src/joints_pose_sender.rs
openrr-teleop/src/robot_command_executor.rs
tools/codegen/src/rpc.rs

This resolves clippy warnings added in Rust 1.66.
- clippy::needless_borrow
- clippy::unnecessary_cast
- clippy::box_default
This also resolves clippy warnings that will be added in Rust 1.67 (currently beta).
- clippy::uninlined_format_args
- clippy::let_underscore_future
See commit messages for actual warnings.

Fix newly added clippy warnings

---

README.md

The following repository was used as a reference.
https://github.com/ashmonty/discord-md-badge

Add badge of link for discord server to README.md

---

Cargo.toml
arci-gamepad-gilrs/Cargo.toml
arci-gamepad-keyboard/Cargo.toml
arci-ros/Cargo.toml
arci-ros/tests/hygiene/Cargo.toml
arci-ros2/Cargo.toml
arci-speak-audio/Cargo.toml
arci-speak-cmd/Cargo.toml
arci-urdf-viz/Cargo.toml
arci/Cargo.toml
openrr-apps/Cargo.toml
openrr-client/Cargo.toml
openrr-command/Cargo.toml
openrr-config/Cargo.toml
openrr-gui/Cargo.toml
openrr-planner/Cargo.toml
openrr-plugin/Cargo.toml
openrr-plugin/examples/plugin/Cargo.toml
openrr-remote/Cargo.toml
openrr-teleop/Cargo.toml
openrr/Cargo.toml
tools/codegen/Cargo.toml

Use workspace inheritance stabilized in Rust 1.64: https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#cargo-improvements-workspace-inheritance-and-multi-target-builds
Refs: https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table

Use workspace inheritance for [package] table

---

openrr-planner/src/collision/self_collision_checker.rs

The currently used `read_file()` function can read URDF files only.

[openrr-planner] Fix to create SelfCollisionChecker from a xacro file

---

arci-ros/tests/test_localization_client.rs
arci-ros/tests/test_robot_client.rs
arci-ros/tests/test_speak_client.rs

The purpose is to increase coverage about `arci-ros`. This time, I implement tests for `RosRobotClient` and `RosSpeakClient`, and `RosLocalizationClient`. But a test of `RosLocalizationClient` does not cover all file lines. `~Builder` and `~Config` is not covered.

[arci-ros] Add test for some `ROS` client.

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/release.yml

Do not wait 6 hours to catch hangs like the one currently occurring in #774.

Set timeout-minutes in all jobs

---

.github/.cspell/project-dictionary.txt
.github/workflows/ci.yml

This reverts commit 22ffb6bbf889017c65fba471eecb9df172abbc0c.
Rust 1.67.1 has been released.

Revert "Temporary use nightly toolchain in tests"

---

README.md
arci-gamepad-gilrs/README.md
arci-gamepad-keyboard/README.md
arci-ros/README.md
arci-ros2/README.md
arci-speak-audio/README.md
arci-speak-cmd/README.md
arci-urdf-viz/README.md
arci/README.md
openrr-apps/README.md
openrr-client/README.md
openrr-command/README.md
openrr-config/README.md
openrr-gui/README.md
openrr-planner/README.md
openrr-plugin/README.md
openrr-remote/README.md
openrr-teleop/README.md

Similar to https://github.com/openrr/urdf-viz/pull/201.
- Fix GitHub Actions badge that points to removed workflow
- Add logo to GitHub Actions and crates.io badges

Update badges in readme

---

README.md

Solve the issue reported in https://github.com/openrr/openrr/issues/814

Fix inactive links to tutorial books

---

.github/workflows/ci.yml

https://github.com/taiki-e/cargo-llvm-cov/releases/tag/v0.5.12
Catch cases where some regions are covered and others are not covered in the same line. For example, if the case that returns Ok is tested, but the case that returns Err is not, the line is marked as partially covered.
~~Blocked on https://github.com/taiki-e/cargo-llvm-cov/issues/252.~~

Enable region coverage on codecov

---

.github/workflows/ci.yml

This will be EoL at the end of this month.
https://wiki.ros.org/Distributions

Remove ROS1 melodic from CI

---

Cargo.toml
arci-ros/src/ros_control/ros_control_action_client.rs
arci-ros/src/ros_localization_client.rs
arci-ros/src/ros_nav_client.rs
arci/src/traits/joint_trajectory_client.rs
arci/tests/test_waits.rs
ci/ubuntu-setup-lld.sh
openrr-plugin/examples/plugin/src/lib.rs

The latest version (0.7.1) is broken.
https://github.com/openrr/openrr/actions/runs/5070455346/jobs/9105512752
<details><summary>log</summary>
```
error[E0599]: no associated item named `ERROR_NONE` found for struct `CancelGoal::Response` in the current scope
--> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/r2r-0.7.1/src/action_clients.rs:253:75
|
253 |                         e if e == action_msgs::srv::CancelGoal::Response::ERROR_NONE as i8 => Ok(()),
|                                                                           ^^^^^^^^^^ associated item not found in `Response`
|
::: /__w/openrr/openrr/target/debug/build/r2r-6f08caf23bc2c702/out/action_msgs.rs:80:27
|
80  |                           pub struct Response {
|                           ------------------- …
```

Fix CI failures

---

openrr-gui/src/joint_position_sender.rs
openrr-gui/src/velocity_sender.rs

In current GUI, we cannot access slide bar in the bottom

Remove max size for GUI

---

openrr-tracing/examples/influxdb.rs

```
error: use of deprecated method `chrono::datetime::DateTime::<Tz>::timestamp_nanos`: use `timestamp_nanos_opt()` instead
--> openrr-tracing/examples/influxdb.rs:57:63
|
57 |             influxdb::Timestamp::Nanoseconds(log[0].timestamp.timestamp_nanos() as _)
|                                                               ^^^^^^^^^^^^^^^
|
= note: `-D deprecated` implied by `-D warnings`
```

[openrr-tracing] Fix deprecated warning from chrono

---

.deny.toml

```
warning[advisory-not-detected]: advisory was not encountered
┌─ /Users/taiki/projects/sources/smilerobotics/openrr/.deny.toml:16:5
│
16 │     "RUSTSEC-2021-0145", # atty 0.2, transitively dep of rosrust (via colored, https://github.com/mackwic/colored/pull/122)
│     ^^^^^^^^^^^^^^^^^^^ no crate matched advisory criteria
```

Remove RUSTSEC-2021-0145 from ignored advisories

---

arci-ros2/examples/navigation.rs
arci-ros2/examples/ros2_cmd_vel.rs
arci-ros2/examples/ros2_control.rs
arci-ros2/src/cmd_vel_move_base.rs
arci-ros2/src/lib.rs
arci-ros2/src/navigation.rs
arci-ros2/src/node.rs
arci-ros2/src/plugin.rs
arci-ros2/src/ros2_control.rs
arci-ros2/src/ros2_laser_scan.rs
arci-ros2/src/utils.rs
arci-ros2/tests/shared/mod.rs
arci-ros2/tests/test_cmd_vel.rs
arci-ros2/tests/test_navigation.rs
arci-ros2/tests/test_ros2_control.rs
arci-ros2/tests/test_ros2_laser_scan.rs

This also unifies the documentation style.
Split from #863.

[arci-ros2] Use Node instead of r2r::Context in API

---

.github/.cspell/project-dictionary.txt
.github/workflows/ci.yml
.markdownlint.yml
README.md
openrr-apps/README.md

This uses markdownlint-cli2, which is used in [vscode-markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint).
```console
$ npx markdownlint-cli2 $(git ls-files '*.md')
markdownlint-cli2 v0.10.0 (markdownlint v0.31.1)
Finding: README.md arci-gamepad-gilrs/README.md arci-gamepad-keyboard/README.md arci-ros/README.md arci-ros2/README.md arci-speak-audio/README.md arci-speak-cmd/README.md arci-urdf-viz/README.md arci/README.md openrr-apps/README.md openrr-client/README.md openrr-command/README.md openrr-config/README.md openrr-gui/README.md openrr-planner/README.md openrr-plugin/README.md openrr-remote/README.md openrr-teleop/README.md openrr-tracing/README.md openrr/README.md
Linting: 20 file(s)
Summary: 8 error(s)
openrr-apps/README.md:190 …
```

Run markdownlint in CI

---

openrr-base/src/odometry.rs

```
error: unused doc comment
--> openrr-base/src/odometry.rs:21:13
|
21 |             /// If `0`, timeout is invalid
|             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22 |             timeout_millis: Mutex::new(DEFAULT_TIMEOUT_MILLIS),
|             -------------------------------------------------- rustdoc does not generate documentation for expression fields
|
= help: use `//` for a plain comment
```

Fix unused_doc_comments warning

---

.github/workflows/ci.yml
arci-ros/tests/hygiene/Cargo.toml
openrr-plugin/benches/proxy.rs
openrr-plugin/examples/plugin/Cargo.toml
tools/codegen/Cargo.toml

Since Rust 1.75, we can omit it.
https://github.com/rust-lang/cargo/commit/307486ed181ac1455767dac866030ce5b67caf67

Use version-less manifests for publish=false crates

---

Cargo.toml

strip is now enabled by default since Rust 1.77. https://blog.rust-lang.org/2024/03/21/Rust-1.77.0.html#enable-strip-in-release-profiles-by-default

Remove strip from profile

---

Cargo.toml
arci-ros/Cargo.toml
arci-ros/src/ros_control/ros_control_action_client.rs
arci-ros/src/ros_control/ros_control_client.rs
arci-ros/src/ros_control/traits.rs
arci-ros/tests/util/mod.rs
arci-ros2/Cargo.toml
arci/Cargo.toml
arci/src/clients/lazy.rs
openrr-plugin/Cargo.toml
openrr-plugin/src/lib.rs

std::sync::LazyLock has been stabilized in Rust 1.80.
The first to third commits are CI fixes from #920.

Use std::sync::{LazyLock,OnceLock} instead of once_cell

---

.deny.toml
.github/.cspell/project-dictionary.txt

```
error[deprecated]: this key has been removed, see https://github.com/EmbarkStudios/cargo-deny/pull/611 for migration information
┌─ /home/runner/work/openrr/openrr/.deny.toml:3:1
│
3 │ vulnerability = "deny"
│ ━━━━━━━━━━━━━
error[deprecated]: this key has been removed, see https://github.com/EmbarkStudios/cargo-deny/pull/611 for migration information
┌─ /home/runner/work/openrr/openrr/.deny.toml:4:1
│
4 │ unmaintained = "allow" # TODO
│ ━━━━━━━━━━━━
error[deprecated]: this key has been removed, see https://github.com/EmbarkStudios/cargo-deny/pull/611 for migration information
┌─ /home/runner/work/openrr/openrr/.deny.toml:5:1
│
5 │ unsound = "deny"
│ ━━━━━━━
error[deprecated]: this key has been removed, see https://github.com/EmbarkStudios/cargo-deny/pull/611 for migration information …
```

Fix CI failure

---

.github/dependabot.yml

This includes two improvements about dependabot:
- Use grouped update: https://github.blog/changelog/2023-08-10-group-dependabot-version-updates-by-development-or-production-dependencies/
This will reduce the number of cases where manual work is required when updating egui or tonic.
- Previously there were various issues with GitHub Actions updates, but perhaps the last major issue was fixed in https://github.com/dependabot/dependabot-core/pull/6743, and now it seems to be working fine (at least to the extent that it was used in github.com/taiki-e and mesh-loader.).

Use grouped update and re-enable Github Actions update of dependabot

---

openrr-planner/src/collision/collision_detector.rs
openrr-planner/src/collision/robot_collision_detector.rs
openrr-planner/src/collision/self_collision_checker.rs
openrr-planner/src/planner/joint_path_planner.rs

Use the `_with_base_dir` variant when loading from the file, otherwise, it will receive error like
```sh
2024-09-04T01:49:24.666406Z ERROR openrr_planner::collision::urdf: ../meshes/collision/link0.stl not found
2024-09-04T01:49:24.666437Z ERROR openrr_planner::collision::urdf: ../meshes/collision/link1.stl not found
2024-09-04T01:49:24.666442Z ERROR openrr_planner::collision::urdf: ../meshes/collision/link2.stl not found
2024-09-04T01:49:24.666447Z ERROR openrr_planner::collision::urdf: ../meshes/collision/link3.stl not found
2024-09-04T01:49:24.666451Z ERROR openrr_planner::collision::urdf: ../meshes/collision/link4.stl not found
2024-09-04T01:49:24.666456Z ERROR openrr_planner::collision::urdf: ../meshes/collision/link5.stl not found
2024-09-04T01:49:24.666461Z ERROR …
```

Use basedir when loading from urdf file

---

.deny.toml

```
error[license-not-encountered]: license was not encountered
┌─ /home/runner/work/openrr/openrr/.deny.toml:35:6
│
35 │     "Unicode-DFS-2016", # unicode-ident
│      ━━━━━━━━━━━━━━━━ unmatched license allowance
```

Update .deny.toml to fix CI failure
